/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { consumersCreate } from "../funcs/consumersCreate.js";
import { consumersDelete } from "../funcs/consumersDelete.js";
import { consumersGet } from "../funcs/consumersGet.js";
import { consumersList } from "../funcs/consumersList.js";
import { consumersUpdate } from "../funcs/consumersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Consumers extends ClientSDK {
  /**
   * Create Consumer
   *
   * @remarks
   * Create a new consumer with contact information and payment details.
   */
  async create(
    security: operations.CreateConsumerApiV2ConsumersPostSecurity,
    request: models.ConsumerCreate,
    options?: RequestOptions,
  ): Promise<models.ConsumerResponse> {
    return unwrapAsync(consumersCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get All Consumers
   *
   * @remarks
   * List all consumers with pagination, filtering, and sorting options.
   */
  async list(
    security: operations.GetAllConsumersApiV2ConsumersGetSecurity,
    request?: operations.GetAllConsumersApiV2ConsumersGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListResourceConsumerResponse> {
    return unwrapAsync(consumersList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Consumer
   *
   * @remarks
   * Retrieve detailed information about a specific consumer by their ID.
   */
  async get(
    security: operations.GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity,
    request: operations.GetConsumerApiV2ConsumersOrgConsumerIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.BaseConsumerResponse> {
    return unwrapAsync(consumersGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update Consumer
   *
   * @remarks
   * Update consumer information such as contact details or payment methods.
   */
  async update(
    security: operations.UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity,
    request: operations.UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.BaseConsumerResponse> {
    return unwrapAsync(consumersUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete Consumer
   *
   * @remarks
   * Delete a consumer from the organization.
   */
  async delete(
    security:
      operations.DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity,
    request: operations.DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(consumersDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
