/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsCreate } from "../funcs/couponsCreate.js";
import { couponsDelete } from "../funcs/couponsDelete.js";
import { couponsGet } from "../funcs/couponsGet.js";
import { couponsList } from "../funcs/couponsList.js";
import { couponsUpdate } from "../funcs/couponsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Coupons extends ClientSDK {
  /**
   * List Coupons
   *
   * @remarks
   * List all coupons with pagination, filtering, and sorting options.
   */
  async list(
    security: operations.ListCouponsApiV2CouponsGetSecurity,
    request?: operations.ListCouponsApiV2CouponsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListResourceCouponDetailed> {
    return unwrapAsync(couponsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create Coupon
   *
   * @remarks
   * Create a new coupon with discount details and active/inactive status.
   */
  async create(
    security: operations.CreateCouponApiV2CouponsPostSecurity,
    request: models.CouponCreate,
    options?: RequestOptions,
  ): Promise<models.CouponDto> {
    return unwrapAsync(couponsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update Coupon
   *
   * @remarks
   * Update coupon details such as discount amount or active status.
   */
  async update(
    security: operations.UpdateCouponApiV2CouponsCouponIdPutSecurity,
    request: operations.UpdateCouponApiV2CouponsCouponIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.CouponDto> {
    return unwrapAsync(couponsUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Coupon
   *
   * @remarks
   * Retrieve detailed information about a specific coupon including redemption history.
   */
  async get(
    security: operations.GetCouponApiV2CouponsCouponIdGetSecurity,
    request: operations.GetCouponApiV2CouponsCouponIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.CouponDetailed> {
    return unwrapAsync(couponsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete Coupon
   *
   * @remarks
   * Delete a coupon from the organization.
   */
  async delete(
    security: operations.DeleteCouponApiV2CouponsCouponIdDeleteSecurity,
    request: operations.DeleteCouponApiV2CouponsCouponIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(couponsDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
