/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsFreezeDelete } from "../funcs/subscriptionsFreezeDelete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Freeze extends ClientSDK {
  /**
   * Delete Subscription Freeze
   *
   * @remarks
   * Remove a freeze period from a subscription.
   */
  async delete(
    security:
      operations.DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity,
    request:
      operations.DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(subscriptionsFreezeDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
