/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGet } from "../funcs/invoicesGet.js";
import { invoicesList } from "../funcs/invoicesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invoices extends ClientSDK {
  /**
   * Get Invoice
   *
   * @remarks
   * Retrieve detailed information about a specific invoice by its ID.
   */
  async get(
    security: operations.GetInvoiceApiV2InvoicesInvoiceIdGetSecurity,
    request: operations.GetInvoiceApiV2InvoicesInvoiceIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.InvoiceDetailed> {
    return unwrapAsync(invoicesGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List Invoices
   *
   * @remarks
   * List all invoices with pagination, filtering, and sorting options.
   */
  async list(
    security: operations.ListInvoicesApiV2InvoicesGetSecurity,
    request: operations.ListInvoicesApiV2InvoicesGetRequest,
    options?: RequestOptions,
  ): Promise<models.ListResourceInvoiceListItem> {
    return unwrapAsync(invoicesList(
      this,
      security,
      request,
      options,
    ));
  }
}
