/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentLinksCreate } from "../funcs/paymentLinksCreate.js";
import { paymentLinksGet } from "../funcs/paymentLinksGet.js";
import { paymentLinksList } from "../funcs/paymentLinksList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PaymentLinks extends ClientSDK {
  /**
   * Get Payment Link
   *
   * @remarks
   * Retrieve detailed information about a specific payment link by its ID.
   */
  async get(
    security:
      operations.GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity,
    request: operations.GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.PaymentLinkDetailed> {
    return unwrapAsync(paymentLinksGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create Payment Link
   *
   * @remarks
   * Create a new payment link for collecting payments.
   */
  async create(
    security: operations.CreatePaymentLinkApiV2PaymentLinksPostSecurity,
    request: models.CreatePaymentLinkDto,
    options?: RequestOptions,
  ): Promise<models.PaymentLinkDetailed> {
    return unwrapAsync(paymentLinksCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List Payment Links
   *
   * @remarks
   * List all payment links with pagination, filtering, and sorting options.
   */
  async list(
    security: operations.ListPaymentLinksApiV2PaymentLinksGetSecurity,
    request: operations.ListPaymentLinksApiV2PaymentLinksGetRequest,
    options?: RequestOptions,
  ): Promise<models.ListResourcePaymentLinkDetailed> {
    return unwrapAsync(paymentLinksList(
      this,
      security,
      request,
      options,
    ));
  }
}
