/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsGet } from "../funcs/paymentsGet.js";
import { paymentsList } from "../funcs/paymentsList.js";
import { paymentsRefund } from "../funcs/paymentsRefund.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * List Payments
   *
   * @remarks
   * List all payments for a specific invoice.
   */
  async list(
    security: operations.ListPaymentsApiV2PaymentsGetSecurity,
    request: operations.ListPaymentsApiV2PaymentsGetRequest,
    options?: RequestOptions,
  ): Promise<models.PaymentListResponse> {
    return unwrapAsync(paymentsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Payment
   *
   * @remarks
   * Retrieve detailed information about a specific payment by its ID.
   */
  async get(
    security: operations.GetPaymentApiV2PaymentsPaymentIdGetSecurity,
    request: operations.GetPaymentApiV2PaymentsPaymentIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.PaymentResponse> {
    return unwrapAsync(paymentsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Refund Payment
   *
   * @remarks
   * Process a refund for a payment.
   */
  async refund(
    security: operations.RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity,
    request: operations.RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest,
    options?: RequestOptions,
  ): Promise<models.PaymentResponse> {
    return unwrapAsync(paymentsRefund(
      this,
      security,
      request,
      options,
    ));
  }
}
