/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsCreate } from "../funcs/productsCreate.js";
import { productsDelete } from "../funcs/productsDelete.js";
import { productsGet } from "../funcs/productsGet.js";
import { productsList } from "../funcs/productsList.js";
import { productsUpdate } from "../funcs/productsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Products extends ClientSDK {
  /**
   * List Products
   *
   * @remarks
   * List all products with pagination, filtering, and sorting options.
   */
  async list(
    security: operations.ListProductsApiV2ProductsGetSecurity,
    request: operations.ListProductsApiV2ProductsGetRequest,
    options?: RequestOptions,
  ): Promise<models.ListResourceProductDto> {
    return unwrapAsync(productsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create Product
   *
   * @remarks
   * Create a new product with pricing and description.
   */
  async create(
    security: operations.CreateProductApiV2ProductsPostSecurity,
    request: models.ProductCreate,
    options?: RequestOptions,
  ): Promise<models.ProductDto> {
    return unwrapAsync(productsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Product
   *
   * @remarks
   * Retrieve detailed information about a specific product by its ID.
   */
  async get(
    security: operations.GetProductApiV2ProductsProductIdGetSecurity,
    request: operations.GetProductApiV2ProductsProductIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.ProductDto> {
    return unwrapAsync(productsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update Product
   *
   * @remarks
   * Update product details such as name, price, or description.
   */
  async update(
    security: operations.UpdateProductApiV2ProductsProductIdPutSecurity,
    request: operations.UpdateProductApiV2ProductsProductIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.ProductDto> {
    return unwrapAsync(productsUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete Product
   *
   * @remarks
   * Delete a product from the organization.
   */
  async delete(
    security: operations.DeleteProductApiV2ProductsProductIdDeleteSecurity,
    request: operations.DeleteProductApiV2ProductsProductIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(productsDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
