/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Consumers } from "./consumers.js";
import { Coupons } from "./coupons.js";
import { Invoices } from "./invoices.js";
import { PaymentLinks } from "./paymentlinks.js";
import { Payments } from "./payments.js";
import { Products } from "./products.js";
import { Subscriptions } from "./subscriptions.js";

export class StreamSDK extends ClientSDK {
  private _consumers?: Consumers;
  get consumers(): Consumers {
    return (this._consumers ??= new Consumers(this._options));
  }

  private _coupons?: Coupons;
  get coupons(): Coupons {
    return (this._coupons ??= new Coupons(this._options));
  }

  private _invoices?: Invoices;
  get invoices(): Invoices {
    return (this._invoices ??= new Invoices(this._options));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }

  private _products?: Products;
  get products(): Products {
    return (this._products ??= new Products(this._options));
  }

  private _subscriptions?: Subscriptions;
  get subscriptions(): Subscriptions {
    return (this._subscriptions ??= new Subscriptions(this._options));
  }

  private _paymentLinks?: PaymentLinks;
  get paymentLinks(): PaymentLinks {
    return (this._paymentLinks ??= new PaymentLinks(this._options));
  }
}
