/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCancel } from "../funcs/subscriptionsCancel.js";
import { subscriptionsCreate } from "../funcs/subscriptionsCreate.js";
import { subscriptionsFreeze } from "../funcs/subscriptionsFreeze.js";
import { subscriptionsGet } from "../funcs/subscriptionsGet.js";
import { subscriptionsList } from "../funcs/subscriptionsList.js";
import { subscriptionsListFreezes } from "../funcs/subscriptionsListFreezes.js";
import { subscriptionsUpdate } from "../funcs/subscriptionsUpdate.js";
import { subscriptionsUpdateFreeze } from "../funcs/subscriptionsUpdateFreeze.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Freeze } from "./freeze.js";

export class Subscriptions extends ClientSDK {
  private _freeze?: Freeze;
  get freeze(): Freeze {
    return (this._freeze ??= new Freeze(this._options));
  }

  /**
   * Get Subscription
   *
   * @remarks
   * Retrieve detailed information about a specific subscription by its ID.
   */
  async get(
    security:
      operations.GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity,
    request:
      operations.GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.SubscriptionDetailed> {
    return unwrapAsync(subscriptionsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update Subscription
   *
   * @remarks
   * Update subscription items, coupons, description, auto-cancel cycles, or payment methods.
   *
   * **Important:** Updates take effect on the next invoice. Changes will not be applied to the current invoice.
   *
   * While updating the subscription, you are only allowed to update:
   * - Items
   * - Coupons
   * - Description
   * - After how many cycles the subscription auto cancel
   * - Payment Methods Overrides
   *
   * To change anything else, you will have to cancel and create a new subscription.
   */
  async update(
    security:
      operations.UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity,
    request:
      operations.UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.SubscriptionDetailed> {
    return unwrapAsync(subscriptionsUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List Subscriptions
   *
   * @remarks
   * List all subscriptions with pagination, filtering, and sorting options.
   */
  async list(
    security: operations.ListSubscriptionsApiV2SubscriptionsGetSecurity,
    request: operations.ListSubscriptionsApiV2SubscriptionsGetRequest,
    options?: RequestOptions,
  ): Promise<models.ListResourceSubscriptionDetailed> {
    return unwrapAsync(subscriptionsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create Subscription
   *
   * @remarks
   * Create a new subscription with items, coupons, and payment methods.
   */
  async create(
    security: operations.CreateSubscriptionApiV2SubscriptionsPostSecurity,
    request: models.SubscriptionCreate,
    options?: RequestOptions,
  ): Promise<models.SubscriptionDetailed> {
    return unwrapAsync(subscriptionsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Cancel Subscription
   *
   * @remarks
   * Cancel a subscription and optionally handle related invoices.
   */
  async cancel(
    security:
      operations.CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity,
    request:
      operations.CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest,
    options?: RequestOptions,
  ): Promise<models.SubscriptionDetailed> {
    return unwrapAsync(subscriptionsCancel(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Freeze Subscription
   *
   * @remarks
   * Freeze a subscription to pause invoice generation for a specific period.
   */
  async freeze(
    security:
      operations.FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity,
    request:
      operations.FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest,
    options?: RequestOptions,
  ): Promise<models.FreezeSubscriptionBase> {
    return unwrapAsync(subscriptionsFreeze(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List Subscription Freezes
   *
   * @remarks
   * List all freeze periods for a specific subscription.
   */
  async listFreezes(
    security:
      operations.ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity,
    request:
      operations.ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest,
    options?: RequestOptions,
  ): Promise<models.ListResourceFreezeSubscriptionBase> {
    return unwrapAsync(subscriptionsListFreezes(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update Subscription Freeze
   *
   * @remarks
   * Update an existing subscription freeze period.
   */
  async updateFreeze(
    security:
      operations.UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity,
    request:
      operations.UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.FreezeSubscriptionBase> {
    return unwrapAsync(subscriptionsUpdateFreeze(
      this,
      security,
      request,
      options,
    ));
  }
}
