/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the stream-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx consumersCreateConsumerApiV2ConsumersPost.example.ts
 */

import { StreamSDK } from "stream-sdk";

const streamSDK = new StreamSDK();

async function main() {
  const result = await streamSDK.consumers.createConsumerApiV2ConsumersPost({
    jwtBearer: process.env["STREAMSDK_JWT_BEARER"] ?? "",
  }, {
    name: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
