/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity =
  {
    jwtBearer?: string | undefined;
    apiKey?: string | undefined;
  };

export type CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest =
  {
    subscriptionId: string;
    body: models.SubscriptionCancel;
  };

/** @internal */
export type CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity$outboundSchema:
  z.ZodMiniType<
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity$Outbound,
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function cancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurityToJSON(
  cancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity:
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity,
): string {
  return JSON.stringify(
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity$outboundSchema
      .parse(
        cancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostSecurity,
      ),
  );
}

/** @internal */
export type CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest$Outbound =
  {
    subscription_id: string;
    body: models.SubscriptionCancel$Outbound;
  };

/** @internal */
export const CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest$outboundSchema:
  z.ZodMiniType<
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest$Outbound,
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      body: models.SubscriptionCancel$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
      });
    }),
  );

export function cancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequestToJSON(
  cancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest:
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest,
): string {
  return JSON.stringify(
    CancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest$outboundSchema
      .parse(
        cancelSubscriptionApiV2SubscriptionsSubscriptionIdCancelPostRequest,
      ),
  );
}
