/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreatePaymentLinkApiV2PaymentLinksPostSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export type CreatePaymentLinkApiV2PaymentLinksPostSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const CreatePaymentLinkApiV2PaymentLinksPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreatePaymentLinkApiV2PaymentLinksPostSecurity$Outbound,
    CreatePaymentLinkApiV2PaymentLinksPostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function createPaymentLinkApiV2PaymentLinksPostSecurityToJSON(
  createPaymentLinkApiV2PaymentLinksPostSecurity:
    CreatePaymentLinkApiV2PaymentLinksPostSecurity,
): string {
  return JSON.stringify(
    CreatePaymentLinkApiV2PaymentLinksPostSecurity$outboundSchema.parse(
      createPaymentLinkApiV2PaymentLinksPostSecurity,
    ),
  );
}
