/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateConsumerApiV2ConsumersPostSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export type CreateConsumerApiV2ConsumersPostSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const CreateConsumerApiV2ConsumersPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateConsumerApiV2ConsumersPostSecurity$Outbound,
    CreateConsumerApiV2ConsumersPostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function createConsumerApiV2ConsumersPostSecurityToJSON(
  createConsumerApiV2ConsumersPostSecurity:
    CreateConsumerApiV2ConsumersPostSecurity,
): string {
  return JSON.stringify(
    CreateConsumerApiV2ConsumersPostSecurity$outboundSchema.parse(
      createConsumerApiV2ConsumersPostSecurity,
    ),
  );
}
