/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateCouponApiV2CouponsPostSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export type CreateCouponApiV2CouponsPostSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const CreateCouponApiV2CouponsPostSecurity$outboundSchema: z.ZodMiniType<
  CreateCouponApiV2CouponsPostSecurity$Outbound,
  CreateCouponApiV2CouponsPostSecurity
> = z.pipe(
  z.object({
    jwtBearer: z.optional(z.string()),
    apiKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      jwtBearer: "JWTBearer",
      apiKey: "APIKey",
    });
  }),
);

export function createCouponApiV2CouponsPostSecurityToJSON(
  createCouponApiV2CouponsPostSecurity: CreateCouponApiV2CouponsPostSecurity,
): string {
  return JSON.stringify(
    CreateCouponApiV2CouponsPostSecurity$outboundSchema.parse(
      createCouponApiV2CouponsPostSecurity,
    ),
  );
}
