/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateSubscriptionApiV2SubscriptionsPostSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export type CreateSubscriptionApiV2SubscriptionsPostSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const CreateSubscriptionApiV2SubscriptionsPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateSubscriptionApiV2SubscriptionsPostSecurity$Outbound,
    CreateSubscriptionApiV2SubscriptionsPostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function createSubscriptionApiV2SubscriptionsPostSecurityToJSON(
  createSubscriptionApiV2SubscriptionsPostSecurity:
    CreateSubscriptionApiV2SubscriptionsPostSecurity,
): string {
  return JSON.stringify(
    CreateSubscriptionApiV2SubscriptionsPostSecurity$outboundSchema.parse(
      createSubscriptionApiV2SubscriptionsPostSecurity,
    ),
  );
}
