/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateProductApiV2ProductsPostSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export type CreateProductApiV2ProductsPostSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const CreateProductApiV2ProductsPostSecurity$outboundSchema:
  z.ZodMiniType<
    CreateProductApiV2ProductsPostSecurity$Outbound,
    CreateProductApiV2ProductsPostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function createProductApiV2ProductsPostSecurityToJSON(
  createProductApiV2ProductsPostSecurity:
    CreateProductApiV2ProductsPostSecurity,
): string {
  return JSON.stringify(
    CreateProductApiV2ProductsPostSecurity$outboundSchema.parse(
      createProductApiV2ProductsPostSecurity,
    ),
  );
}
