/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity =
  {
    jwtBearer?: string | undefined;
    apiKey?: string | undefined;
  };

export type DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest =
  {
    subscriptionId: string;
    freezeId: string;
  };

/** @internal */
export type DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity$Outbound,
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function deleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurityToJSON(
  deleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity:
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity$outboundSchema
      .parse(
        deleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteSecurity,
      ),
  );
}

/** @internal */
export type DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest$Outbound =
  {
    subscription_id: string;
    freeze_id: string;
  };

/** @internal */
export const DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest$Outbound,
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      freezeId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
        freezeId: "freeze_id",
      });
    }),
  );

export function deleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequestToJSON(
  deleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest:
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest$outboundSchema
      .parse(
        deleteSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdDeleteRequest,
      ),
  );
}
