/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteProductApiV2ProductsProductIdDeleteSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type DeleteProductApiV2ProductsProductIdDeleteRequest = {
  productId: string;
};

/** @internal */
export type DeleteProductApiV2ProductsProductIdDeleteSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const DeleteProductApiV2ProductsProductIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteProductApiV2ProductsProductIdDeleteSecurity$Outbound,
    DeleteProductApiV2ProductsProductIdDeleteSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function deleteProductApiV2ProductsProductIdDeleteSecurityToJSON(
  deleteProductApiV2ProductsProductIdDeleteSecurity:
    DeleteProductApiV2ProductsProductIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteProductApiV2ProductsProductIdDeleteSecurity$outboundSchema.parse(
      deleteProductApiV2ProductsProductIdDeleteSecurity,
    ),
  );
}

/** @internal */
export type DeleteProductApiV2ProductsProductIdDeleteRequest$Outbound = {
  product_id: string;
};

/** @internal */
export const DeleteProductApiV2ProductsProductIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteProductApiV2ProductsProductIdDeleteRequest$Outbound,
    DeleteProductApiV2ProductsProductIdDeleteRequest
  > = z.pipe(
    z.object({
      productId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        productId: "product_id",
      });
    }),
  );

export function deleteProductApiV2ProductsProductIdDeleteRequestToJSON(
  deleteProductApiV2ProductsProductIdDeleteRequest:
    DeleteProductApiV2ProductsProductIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteProductApiV2ProductsProductIdDeleteRequest$outboundSchema.parse(
      deleteProductApiV2ProductsProductIdDeleteRequest,
    ),
  );
}
