/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest = {
  orgConsumerId: string;
};

/** @internal */
export type DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity$Outbound,
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function deleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurityToJSON(
  deleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity:
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity$outboundSchema
      .parse(deleteConsumerApiV2ConsumersOrgConsumerIdDeleteSecurity),
  );
}

/** @internal */
export type DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest$Outbound = {
  org_consumer_id: string;
};

/** @internal */
export const DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest$Outbound,
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest
  > = z.pipe(
    z.object({
      orgConsumerId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        orgConsumerId: "org_consumer_id",
      });
    }),
  );

export function deleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequestToJSON(
  deleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest:
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest$outboundSchema.parse(
      deleteConsumerApiV2ConsumersOrgConsumerIdDeleteRequest,
    ),
  );
}
