/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteCouponApiV2CouponsCouponIdDeleteSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type DeleteCouponApiV2CouponsCouponIdDeleteRequest = {
  couponId: string;
};

/** @internal */
export type DeleteCouponApiV2CouponsCouponIdDeleteSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const DeleteCouponApiV2CouponsCouponIdDeleteSecurity$outboundSchema:
  z.ZodMiniType<
    DeleteCouponApiV2CouponsCouponIdDeleteSecurity$Outbound,
    DeleteCouponApiV2CouponsCouponIdDeleteSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function deleteCouponApiV2CouponsCouponIdDeleteSecurityToJSON(
  deleteCouponApiV2CouponsCouponIdDeleteSecurity:
    DeleteCouponApiV2CouponsCouponIdDeleteSecurity,
): string {
  return JSON.stringify(
    DeleteCouponApiV2CouponsCouponIdDeleteSecurity$outboundSchema.parse(
      deleteCouponApiV2CouponsCouponIdDeleteSecurity,
    ),
  );
}

/** @internal */
export type DeleteCouponApiV2CouponsCouponIdDeleteRequest$Outbound = {
  coupon_id: string;
};

/** @internal */
export const DeleteCouponApiV2CouponsCouponIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteCouponApiV2CouponsCouponIdDeleteRequest$Outbound,
    DeleteCouponApiV2CouponsCouponIdDeleteRequest
  > = z.pipe(
    z.object({
      couponId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        couponId: "coupon_id",
      });
    }),
  );

export function deleteCouponApiV2CouponsCouponIdDeleteRequestToJSON(
  deleteCouponApiV2CouponsCouponIdDeleteRequest:
    DeleteCouponApiV2CouponsCouponIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteCouponApiV2CouponsCouponIdDeleteRequest$outboundSchema.parse(
      deleteCouponApiV2CouponsCouponIdDeleteRequest,
    ),
  );
}
