/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity =
  {
    jwtBearer?: string | undefined;
    apiKey?: string | undefined;
  };

export type FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest =
  {
    subscriptionId: string;
    body: models.FreezeSubscriptionCreateRequest;
  };

/** @internal */
export type FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity$outboundSchema:
  z.ZodMiniType<
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity$Outbound,
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function freezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurityToJSON(
  freezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity:
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity,
): string {
  return JSON.stringify(
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity$outboundSchema
      .parse(
        freezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostSecurity,
      ),
  );
}

/** @internal */
export type FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest$Outbound =
  {
    subscription_id: string;
    body: models.FreezeSubscriptionCreateRequest$Outbound;
  };

/** @internal */
export const FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest$outboundSchema:
  z.ZodMiniType<
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest$Outbound,
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      body: models.FreezeSubscriptionCreateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
      });
    }),
  );

export function freezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequestToJSON(
  freezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest:
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest,
): string {
  return JSON.stringify(
    FreezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest$outboundSchema
      .parse(
        freezeSubscriptionApiV2SubscriptionsSubscriptionIdFreezePostRequest,
      ),
  );
}
