/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetAllConsumersApiV2ConsumersGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetAllConsumersApiV2ConsumersGetRequest = {
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  searchTerm?: string | null | undefined;
  /**
   * Field to sort by, e.g., 'amount', 'scheduled_on'
   */
  sortField?: string | null | undefined;
  /**
   * Sorting direction ('asc' or 'desc')
   */
  sortDirection?: string | null | undefined;
};

/** @internal */
export type GetAllConsumersApiV2ConsumersGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetAllConsumersApiV2ConsumersGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetAllConsumersApiV2ConsumersGetSecurity$Outbound,
    GetAllConsumersApiV2ConsumersGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getAllConsumersApiV2ConsumersGetSecurityToJSON(
  getAllConsumersApiV2ConsumersGetSecurity:
    GetAllConsumersApiV2ConsumersGetSecurity,
): string {
  return JSON.stringify(
    GetAllConsumersApiV2ConsumersGetSecurity$outboundSchema.parse(
      getAllConsumersApiV2ConsumersGetSecurity,
    ),
  );
}

/** @internal */
export type GetAllConsumersApiV2ConsumersGetRequest$Outbound = {
  page: number;
  limit: number;
  search_term?: string | null | undefined;
  sort_field?: string | null | undefined;
  sort_direction?: string | null | undefined;
};

/** @internal */
export const GetAllConsumersApiV2ConsumersGetRequest$outboundSchema:
  z.ZodMiniType<
    GetAllConsumersApiV2ConsumersGetRequest$Outbound,
    GetAllConsumersApiV2ConsumersGetRequest
  > = z.pipe(
    z.object({
      page: z._default(z.int(), 1),
      limit: z._default(z.int(), 10),
      searchTerm: z.optional(z.nullable(z.string())),
      sortField: z.optional(z.nullable(z.string())),
      sortDirection: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        searchTerm: "search_term",
        sortField: "sort_field",
        sortDirection: "sort_direction",
      });
    }),
  );

export function getAllConsumersApiV2ConsumersGetRequestToJSON(
  getAllConsumersApiV2ConsumersGetRequest:
    GetAllConsumersApiV2ConsumersGetRequest,
): string {
  return JSON.stringify(
    GetAllConsumersApiV2ConsumersGetRequest$outboundSchema.parse(
      getAllConsumersApiV2ConsumersGetRequest,
    ),
  );
}
