/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetConsumerApiV2ConsumersOrgConsumerIdGetRequest = {
  orgConsumerId: string;
};

/** @internal */
export type GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity$Outbound,
    GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getConsumerApiV2ConsumersOrgConsumerIdGetSecurityToJSON(
  getConsumerApiV2ConsumersOrgConsumerIdGetSecurity:
    GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity,
): string {
  return JSON.stringify(
    GetConsumerApiV2ConsumersOrgConsumerIdGetSecurity$outboundSchema.parse(
      getConsumerApiV2ConsumersOrgConsumerIdGetSecurity,
    ),
  );
}

/** @internal */
export type GetConsumerApiV2ConsumersOrgConsumerIdGetRequest$Outbound = {
  org_consumer_id: string;
};

/** @internal */
export const GetConsumerApiV2ConsumersOrgConsumerIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetConsumerApiV2ConsumersOrgConsumerIdGetRequest$Outbound,
    GetConsumerApiV2ConsumersOrgConsumerIdGetRequest
  > = z.pipe(
    z.object({
      orgConsumerId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        orgConsumerId: "org_consumer_id",
      });
    }),
  );

export function getConsumerApiV2ConsumersOrgConsumerIdGetRequestToJSON(
  getConsumerApiV2ConsumersOrgConsumerIdGetRequest:
    GetConsumerApiV2ConsumersOrgConsumerIdGetRequest,
): string {
  return JSON.stringify(
    GetConsumerApiV2ConsumersOrgConsumerIdGetRequest$outboundSchema.parse(
      getConsumerApiV2ConsumersOrgConsumerIdGetRequest,
    ),
  );
}
