/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetCouponApiV2CouponsCouponIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetCouponApiV2CouponsCouponIdGetRequest = {
  couponId: string;
};

/** @internal */
export type GetCouponApiV2CouponsCouponIdGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetCouponApiV2CouponsCouponIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetCouponApiV2CouponsCouponIdGetSecurity$Outbound,
    GetCouponApiV2CouponsCouponIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getCouponApiV2CouponsCouponIdGetSecurityToJSON(
  getCouponApiV2CouponsCouponIdGetSecurity:
    GetCouponApiV2CouponsCouponIdGetSecurity,
): string {
  return JSON.stringify(
    GetCouponApiV2CouponsCouponIdGetSecurity$outboundSchema.parse(
      getCouponApiV2CouponsCouponIdGetSecurity,
    ),
  );
}

/** @internal */
export type GetCouponApiV2CouponsCouponIdGetRequest$Outbound = {
  coupon_id: string;
};

/** @internal */
export const GetCouponApiV2CouponsCouponIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetCouponApiV2CouponsCouponIdGetRequest$Outbound,
    GetCouponApiV2CouponsCouponIdGetRequest
  > = z.pipe(
    z.object({
      couponId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        couponId: "coupon_id",
      });
    }),
  );

export function getCouponApiV2CouponsCouponIdGetRequestToJSON(
  getCouponApiV2CouponsCouponIdGetRequest:
    GetCouponApiV2CouponsCouponIdGetRequest,
): string {
  return JSON.stringify(
    GetCouponApiV2CouponsCouponIdGetRequest$outboundSchema.parse(
      getCouponApiV2CouponsCouponIdGetRequest,
    ),
  );
}
