/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetInvoiceApiV2InvoicesInvoiceIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetInvoiceApiV2InvoicesInvoiceIdGetRequest = {
  invoiceId: string;
};

/** @internal */
export type GetInvoiceApiV2InvoicesInvoiceIdGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetInvoiceApiV2InvoicesInvoiceIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetInvoiceApiV2InvoicesInvoiceIdGetSecurity$Outbound,
    GetInvoiceApiV2InvoicesInvoiceIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getInvoiceApiV2InvoicesInvoiceIdGetSecurityToJSON(
  getInvoiceApiV2InvoicesInvoiceIdGetSecurity:
    GetInvoiceApiV2InvoicesInvoiceIdGetSecurity,
): string {
  return JSON.stringify(
    GetInvoiceApiV2InvoicesInvoiceIdGetSecurity$outboundSchema.parse(
      getInvoiceApiV2InvoicesInvoiceIdGetSecurity,
    ),
  );
}

/** @internal */
export type GetInvoiceApiV2InvoicesInvoiceIdGetRequest$Outbound = {
  invoice_id: string;
};

/** @internal */
export const GetInvoiceApiV2InvoicesInvoiceIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetInvoiceApiV2InvoicesInvoiceIdGetRequest$Outbound,
    GetInvoiceApiV2InvoicesInvoiceIdGetRequest
  > = z.pipe(
    z.object({
      invoiceId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        invoiceId: "invoice_id",
      });
    }),
  );

export function getInvoiceApiV2InvoicesInvoiceIdGetRequestToJSON(
  getInvoiceApiV2InvoicesInvoiceIdGetRequest:
    GetInvoiceApiV2InvoicesInvoiceIdGetRequest,
): string {
  return JSON.stringify(
    GetInvoiceApiV2InvoicesInvoiceIdGetRequest$outboundSchema.parse(
      getInvoiceApiV2InvoicesInvoiceIdGetRequest,
    ),
  );
}
