/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetProductApiV2ProductsProductIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetProductApiV2ProductsProductIdGetRequest = {
  productId: string;
};

/** @internal */
export type GetProductApiV2ProductsProductIdGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetProductApiV2ProductsProductIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetProductApiV2ProductsProductIdGetSecurity$Outbound,
    GetProductApiV2ProductsProductIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getProductApiV2ProductsProductIdGetSecurityToJSON(
  getProductApiV2ProductsProductIdGetSecurity:
    GetProductApiV2ProductsProductIdGetSecurity,
): string {
  return JSON.stringify(
    GetProductApiV2ProductsProductIdGetSecurity$outboundSchema.parse(
      getProductApiV2ProductsProductIdGetSecurity,
    ),
  );
}

/** @internal */
export type GetProductApiV2ProductsProductIdGetRequest$Outbound = {
  product_id: string;
};

/** @internal */
export const GetProductApiV2ProductsProductIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetProductApiV2ProductsProductIdGetRequest$Outbound,
    GetProductApiV2ProductsProductIdGetRequest
  > = z.pipe(
    z.object({
      productId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        productId: "product_id",
      });
    }),
  );

export function getProductApiV2ProductsProductIdGetRequestToJSON(
  getProductApiV2ProductsProductIdGetRequest:
    GetProductApiV2ProductsProductIdGetRequest,
): string {
  return JSON.stringify(
    GetProductApiV2ProductsProductIdGetRequest$outboundSchema.parse(
      getProductApiV2ProductsProductIdGetRequest,
    ),
  );
}
