/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPaymentApiV2PaymentsPaymentIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetPaymentApiV2PaymentsPaymentIdGetRequest = {
  paymentId: string;
};

/** @internal */
export type GetPaymentApiV2PaymentsPaymentIdGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetPaymentApiV2PaymentsPaymentIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetPaymentApiV2PaymentsPaymentIdGetSecurity$Outbound,
    GetPaymentApiV2PaymentsPaymentIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getPaymentApiV2PaymentsPaymentIdGetSecurityToJSON(
  getPaymentApiV2PaymentsPaymentIdGetSecurity:
    GetPaymentApiV2PaymentsPaymentIdGetSecurity,
): string {
  return JSON.stringify(
    GetPaymentApiV2PaymentsPaymentIdGetSecurity$outboundSchema.parse(
      getPaymentApiV2PaymentsPaymentIdGetSecurity,
    ),
  );
}

/** @internal */
export type GetPaymentApiV2PaymentsPaymentIdGetRequest$Outbound = {
  payment_id: string;
};

/** @internal */
export const GetPaymentApiV2PaymentsPaymentIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPaymentApiV2PaymentsPaymentIdGetRequest$Outbound,
    GetPaymentApiV2PaymentsPaymentIdGetRequest
  > = z.pipe(
    z.object({
      paymentId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        paymentId: "payment_id",
      });
    }),
  );

export function getPaymentApiV2PaymentsPaymentIdGetRequestToJSON(
  getPaymentApiV2PaymentsPaymentIdGetRequest:
    GetPaymentApiV2PaymentsPaymentIdGetRequest,
): string {
  return JSON.stringify(
    GetPaymentApiV2PaymentsPaymentIdGetRequest$outboundSchema.parse(
      getPaymentApiV2PaymentsPaymentIdGetRequest,
    ),
  );
}
