/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest = {
  paymentLinkId: string;
};

/** @internal */
export type GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity$Outbound,
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurityToJSON(
  getPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity:
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity,
): string {
  return JSON.stringify(
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity$outboundSchema
      .parse(getPaymentLinkApiV2PaymentLinksPaymentLinkIdGetSecurity),
  );
}

/** @internal */
export type GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest$Outbound = {
  payment_link_id: string;
};

/** @internal */
export const GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest$Outbound,
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest
  > = z.pipe(
    z.object({
      paymentLinkId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        paymentLinkId: "payment_link_id",
      });
    }),
  );

export function getPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequestToJSON(
  getPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest:
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest,
): string {
  return JSON.stringify(
    GetPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest$outboundSchema.parse(
      getPaymentLinkApiV2PaymentLinksPaymentLinkIdGetRequest,
    ),
  );
}
