/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest = {
  subscriptionId: string;
};

/** @internal */
export type GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity$Outbound,
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function getSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurityToJSON(
  getSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity:
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity,
): string {
  return JSON.stringify(
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity$outboundSchema
      .parse(getSubscriptionApiV2SubscriptionsSubscriptionIdGetSecurity),
  );
}

/** @internal */
export type GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest$Outbound =
  {
    subscription_id: string;
  };

/** @internal */
export const GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest$Outbound,
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
      });
    }),
  );

export function getSubscriptionApiV2SubscriptionsSubscriptionIdGetRequestToJSON(
  getSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest:
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest,
): string {
  return JSON.stringify(
    GetSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest$outboundSchema
      .parse(getSubscriptionApiV2SubscriptionsSubscriptionIdGetRequest),
  );
}
