/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListProductsApiV2ProductsGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type ListProductsApiV2ProductsGetRequest = {
  filters: models.ProductListFilters;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Field to sort by, e.g., 'amount', 'scheduled_on'
   */
  sortField?: string | null | undefined;
  /**
   * Sorting direction ('asc' or 'desc')
   */
  sortDirection?: string | null | undefined;
};

/** @internal */
export type ListProductsApiV2ProductsGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const ListProductsApiV2ProductsGetSecurity$outboundSchema: z.ZodMiniType<
  ListProductsApiV2ProductsGetSecurity$Outbound,
  ListProductsApiV2ProductsGetSecurity
> = z.pipe(
  z.object({
    jwtBearer: z.optional(z.string()),
    apiKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      jwtBearer: "JWTBearer",
      apiKey: "APIKey",
    });
  }),
);

export function listProductsApiV2ProductsGetSecurityToJSON(
  listProductsApiV2ProductsGetSecurity: ListProductsApiV2ProductsGetSecurity,
): string {
  return JSON.stringify(
    ListProductsApiV2ProductsGetSecurity$outboundSchema.parse(
      listProductsApiV2ProductsGetSecurity,
    ),
  );
}

/** @internal */
export type ListProductsApiV2ProductsGetRequest$Outbound = {
  filters: models.ProductListFilters$Outbound;
  page: number;
  limit: number;
  sort_field?: string | null | undefined;
  sort_direction?: string | null | undefined;
};

/** @internal */
export const ListProductsApiV2ProductsGetRequest$outboundSchema: z.ZodMiniType<
  ListProductsApiV2ProductsGetRequest$Outbound,
  ListProductsApiV2ProductsGetRequest
> = z.pipe(
  z.object({
    filters: models.ProductListFilters$outboundSchema,
    page: z._default(z.int(), 1),
    limit: z._default(z.int(), 10),
    sortField: z.optional(z.nullable(z.string())),
    sortDirection: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      sortField: "sort_field",
      sortDirection: "sort_direction",
    });
  }),
);

export function listProductsApiV2ProductsGetRequestToJSON(
  listProductsApiV2ProductsGetRequest: ListProductsApiV2ProductsGetRequest,
): string {
  return JSON.stringify(
    ListProductsApiV2ProductsGetRequest$outboundSchema.parse(
      listProductsApiV2ProductsGetRequest,
    ),
  );
}
