/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListInvoicesApiV2InvoicesGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type ListInvoicesApiV2InvoicesGetRequest = {
  filters: models.InvoiceListFilters;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Field to sort by, e.g., 'amount', 'scheduled_on'
   */
  sortField?: string | null | undefined;
  /**
   * Sorting direction ('asc' or 'desc')
   */
  sortDirection?: string | null | undefined;
};

/** @internal */
export type ListInvoicesApiV2InvoicesGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const ListInvoicesApiV2InvoicesGetSecurity$outboundSchema: z.ZodMiniType<
  ListInvoicesApiV2InvoicesGetSecurity$Outbound,
  ListInvoicesApiV2InvoicesGetSecurity
> = z.pipe(
  z.object({
    jwtBearer: z.optional(z.string()),
    apiKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      jwtBearer: "JWTBearer",
      apiKey: "APIKey",
    });
  }),
);

export function listInvoicesApiV2InvoicesGetSecurityToJSON(
  listInvoicesApiV2InvoicesGetSecurity: ListInvoicesApiV2InvoicesGetSecurity,
): string {
  return JSON.stringify(
    ListInvoicesApiV2InvoicesGetSecurity$outboundSchema.parse(
      listInvoicesApiV2InvoicesGetSecurity,
    ),
  );
}

/** @internal */
export type ListInvoicesApiV2InvoicesGetRequest$Outbound = {
  filters: models.InvoiceListFilters$Outbound;
  page: number;
  limit: number;
  sort_field?: string | null | undefined;
  sort_direction?: string | null | undefined;
};

/** @internal */
export const ListInvoicesApiV2InvoicesGetRequest$outboundSchema: z.ZodMiniType<
  ListInvoicesApiV2InvoicesGetRequest$Outbound,
  ListInvoicesApiV2InvoicesGetRequest
> = z.pipe(
  z.object({
    filters: models.InvoiceListFilters$outboundSchema,
    page: z._default(z.int(), 1),
    limit: z._default(z.int(), 10),
    sortField: z.optional(z.nullable(z.string())),
    sortDirection: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      sortField: "sort_field",
      sortDirection: "sort_direction",
    });
  }),
);

export function listInvoicesApiV2InvoicesGetRequestToJSON(
  listInvoicesApiV2InvoicesGetRequest: ListInvoicesApiV2InvoicesGetRequest,
): string {
  return JSON.stringify(
    ListInvoicesApiV2InvoicesGetRequest$outboundSchema.parse(
      listInvoicesApiV2InvoicesGetRequest,
    ),
  );
}
