/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity =
  {
    jwtBearer?: string | undefined;
    apiKey?: string | undefined;
  };

export type ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest =
  {
    subscriptionId: string;
    /**
     * Page number, defaults to 1.
     */
    page?: number | undefined;
    /**
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number | undefined;
    /**
     * Field to sort by, e.g., 'amount', 'scheduled_on'
     */
    sortField?: string | null | undefined;
    /**
     * Sorting direction ('asc' or 'desc')
     */
    sortDirection?: string | null | undefined;
  };

/** @internal */
export type ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity$outboundSchema:
  z.ZodMiniType<
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity$Outbound,
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function listSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurityToJSON(
  listSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity:
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity,
): string {
  return JSON.stringify(
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity$outboundSchema
      .parse(
        listSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetSecurity,
      ),
  );
}

/** @internal */
export type ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest$Outbound =
  {
    subscription_id: string;
    page: number;
    limit: number;
    sort_field?: string | null | undefined;
    sort_direction?: string | null | undefined;
  };

/** @internal */
export const ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest$outboundSchema:
  z.ZodMiniType<
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest$Outbound,
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      page: z._default(z.int(), 1),
      limit: z._default(z.int(), 10),
      sortField: z.optional(z.nullable(z.string())),
      sortDirection: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
        sortField: "sort_field",
        sortDirection: "sort_direction",
      });
    }),
  );

export function listSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequestToJSON(
  listSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest:
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest,
): string {
  return JSON.stringify(
    ListSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest$outboundSchema
      .parse(
        listSubscriptionFreezesApiV2SubscriptionsSubscriptionIdFreezeGetRequest,
      ),
  );
}
