/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListPaymentsApiV2PaymentsGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type ListPaymentsApiV2PaymentsGetRequest = {
  invoiceId: string;
};

/** @internal */
export type ListPaymentsApiV2PaymentsGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const ListPaymentsApiV2PaymentsGetSecurity$outboundSchema: z.ZodMiniType<
  ListPaymentsApiV2PaymentsGetSecurity$Outbound,
  ListPaymentsApiV2PaymentsGetSecurity
> = z.pipe(
  z.object({
    jwtBearer: z.optional(z.string()),
    apiKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      jwtBearer: "JWTBearer",
      apiKey: "APIKey",
    });
  }),
);

export function listPaymentsApiV2PaymentsGetSecurityToJSON(
  listPaymentsApiV2PaymentsGetSecurity: ListPaymentsApiV2PaymentsGetSecurity,
): string {
  return JSON.stringify(
    ListPaymentsApiV2PaymentsGetSecurity$outboundSchema.parse(
      listPaymentsApiV2PaymentsGetSecurity,
    ),
  );
}

/** @internal */
export type ListPaymentsApiV2PaymentsGetRequest$Outbound = {
  invoice_id: string;
};

/** @internal */
export const ListPaymentsApiV2PaymentsGetRequest$outboundSchema: z.ZodMiniType<
  ListPaymentsApiV2PaymentsGetRequest$Outbound,
  ListPaymentsApiV2PaymentsGetRequest
> = z.pipe(
  z.object({
    invoiceId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoiceId: "invoice_id",
    });
  }),
);

export function listPaymentsApiV2PaymentsGetRequestToJSON(
  listPaymentsApiV2PaymentsGetRequest: ListPaymentsApiV2PaymentsGetRequest,
): string {
  return JSON.stringify(
    ListPaymentsApiV2PaymentsGetRequest$outboundSchema.parse(
      listPaymentsApiV2PaymentsGetRequest,
    ),
  );
}
