/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListSubscriptionsApiV2SubscriptionsGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type ListSubscriptionsApiV2SubscriptionsGetRequest = {
  filters: models.SubscriptionListFilters;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Field to sort by, e.g., 'amount', 'scheduled_on'
   */
  sortField?: string | null | undefined;
  /**
   * Sorting direction ('asc' or 'desc')
   */
  sortDirection?: string | null | undefined;
};

/** @internal */
export type ListSubscriptionsApiV2SubscriptionsGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const ListSubscriptionsApiV2SubscriptionsGetSecurity$outboundSchema:
  z.ZodMiniType<
    ListSubscriptionsApiV2SubscriptionsGetSecurity$Outbound,
    ListSubscriptionsApiV2SubscriptionsGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function listSubscriptionsApiV2SubscriptionsGetSecurityToJSON(
  listSubscriptionsApiV2SubscriptionsGetSecurity:
    ListSubscriptionsApiV2SubscriptionsGetSecurity,
): string {
  return JSON.stringify(
    ListSubscriptionsApiV2SubscriptionsGetSecurity$outboundSchema.parse(
      listSubscriptionsApiV2SubscriptionsGetSecurity,
    ),
  );
}

/** @internal */
export type ListSubscriptionsApiV2SubscriptionsGetRequest$Outbound = {
  filters: models.SubscriptionListFilters$Outbound;
  page: number;
  limit: number;
  sort_field?: string | null | undefined;
  sort_direction?: string | null | undefined;
};

/** @internal */
export const ListSubscriptionsApiV2SubscriptionsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListSubscriptionsApiV2SubscriptionsGetRequest$Outbound,
    ListSubscriptionsApiV2SubscriptionsGetRequest
  > = z.pipe(
    z.object({
      filters: models.SubscriptionListFilters$outboundSchema,
      page: z._default(z.int(), 1),
      limit: z._default(z.int(), 10),
      sortField: z.optional(z.nullable(z.string())),
      sortDirection: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        sortField: "sort_field",
        sortDirection: "sort_direction",
      });
    }),
  );

export function listSubscriptionsApiV2SubscriptionsGetRequestToJSON(
  listSubscriptionsApiV2SubscriptionsGetRequest:
    ListSubscriptionsApiV2SubscriptionsGetRequest,
): string {
  return JSON.stringify(
    ListSubscriptionsApiV2SubscriptionsGetRequest$outboundSchema.parse(
      listSubscriptionsApiV2SubscriptionsGetRequest,
    ),
  );
}
