/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListPaymentLinksApiV2PaymentLinksGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type ListPaymentLinksApiV2PaymentLinksGetRequest = {
  filters: models.PaymentLinkListFilters;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Field to sort by, e.g., 'amount', 'scheduled_on'
   */
  sortField?: string | null | undefined;
  /**
   * Sorting direction ('asc' or 'desc')
   */
  sortDirection?: string | null | undefined;
};

/** @internal */
export type ListPaymentLinksApiV2PaymentLinksGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const ListPaymentLinksApiV2PaymentLinksGetSecurity$outboundSchema:
  z.ZodMiniType<
    ListPaymentLinksApiV2PaymentLinksGetSecurity$Outbound,
    ListPaymentLinksApiV2PaymentLinksGetSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function listPaymentLinksApiV2PaymentLinksGetSecurityToJSON(
  listPaymentLinksApiV2PaymentLinksGetSecurity:
    ListPaymentLinksApiV2PaymentLinksGetSecurity,
): string {
  return JSON.stringify(
    ListPaymentLinksApiV2PaymentLinksGetSecurity$outboundSchema.parse(
      listPaymentLinksApiV2PaymentLinksGetSecurity,
    ),
  );
}

/** @internal */
export type ListPaymentLinksApiV2PaymentLinksGetRequest$Outbound = {
  filters: models.PaymentLinkListFilters$Outbound;
  page: number;
  limit: number;
  sort_field?: string | null | undefined;
  sort_direction?: string | null | undefined;
};

/** @internal */
export const ListPaymentLinksApiV2PaymentLinksGetRequest$outboundSchema:
  z.ZodMiniType<
    ListPaymentLinksApiV2PaymentLinksGetRequest$Outbound,
    ListPaymentLinksApiV2PaymentLinksGetRequest
  > = z.pipe(
    z.object({
      filters: models.PaymentLinkListFilters$outboundSchema,
      page: z._default(z.int(), 1),
      limit: z._default(z.int(), 10),
      sortField: z.optional(z.nullable(z.string())),
      sortDirection: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        sortField: "sort_field",
        sortDirection: "sort_direction",
      });
    }),
  );

export function listPaymentLinksApiV2PaymentLinksGetRequestToJSON(
  listPaymentLinksApiV2PaymentLinksGetRequest:
    ListPaymentLinksApiV2PaymentLinksGetRequest,
): string {
  return JSON.stringify(
    ListPaymentLinksApiV2PaymentLinksGetRequest$outboundSchema.parse(
      listPaymentLinksApiV2PaymentLinksGetRequest,
    ),
  );
}
