/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListCouponsApiV2CouponsGetSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type ListCouponsApiV2CouponsGetRequest = {
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Search by coupon name.
   */
  searchTerm?: string | null | undefined;
  /**
   * Filter by active or inactive coupons.
   */
  active?: boolean | null | undefined;
  /**
   * Filter by percentage-based or fixed-amount coupons.
   */
  isPercentage?: boolean | null | undefined;
  /**
   * Field to sort by, e.g., 'amount', 'scheduled_on'
   */
  sortField?: string | null | undefined;
  /**
   * Sorting direction ('asc' or 'desc')
   */
  sortDirection?: string | null | undefined;
};

/** @internal */
export type ListCouponsApiV2CouponsGetSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const ListCouponsApiV2CouponsGetSecurity$outboundSchema: z.ZodMiniType<
  ListCouponsApiV2CouponsGetSecurity$Outbound,
  ListCouponsApiV2CouponsGetSecurity
> = z.pipe(
  z.object({
    jwtBearer: z.optional(z.string()),
    apiKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      jwtBearer: "JWTBearer",
      apiKey: "APIKey",
    });
  }),
);

export function listCouponsApiV2CouponsGetSecurityToJSON(
  listCouponsApiV2CouponsGetSecurity: ListCouponsApiV2CouponsGetSecurity,
): string {
  return JSON.stringify(
    ListCouponsApiV2CouponsGetSecurity$outboundSchema.parse(
      listCouponsApiV2CouponsGetSecurity,
    ),
  );
}

/** @internal */
export type ListCouponsApiV2CouponsGetRequest$Outbound = {
  page: number;
  limit: number;
  search_term?: string | null | undefined;
  active?: boolean | null | undefined;
  is_percentage?: boolean | null | undefined;
  sort_field?: string | null | undefined;
  sort_direction?: string | null | undefined;
};

/** @internal */
export const ListCouponsApiV2CouponsGetRequest$outboundSchema: z.ZodMiniType<
  ListCouponsApiV2CouponsGetRequest$Outbound,
  ListCouponsApiV2CouponsGetRequest
> = z.pipe(
  z.object({
    page: z._default(z.int(), 1),
    limit: z._default(z.int(), 10),
    searchTerm: z.optional(z.nullable(z.string())),
    active: z.optional(z.nullable(z.boolean())),
    isPercentage: z.optional(z.nullable(z.boolean())),
    sortField: z.optional(z.nullable(z.string())),
    sortDirection: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      searchTerm: "search_term",
      isPercentage: "is_percentage",
      sortField: "sort_field",
      sortDirection: "sort_direction",
    });
  }),
);

export function listCouponsApiV2CouponsGetRequestToJSON(
  listCouponsApiV2CouponsGetRequest: ListCouponsApiV2CouponsGetRequest,
): string {
  return JSON.stringify(
    ListCouponsApiV2CouponsGetRequest$outboundSchema.parse(
      listCouponsApiV2CouponsGetRequest,
    ),
  );
}
