/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest = {
  paymentId: string;
  body: models.PaymentRefundRequest;
};

/** @internal */
export type RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity$outboundSchema:
  z.ZodMiniType<
    RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity$Outbound,
    RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function refundPaymentApiV2PaymentsPaymentIdRefundPostSecurityToJSON(
  refundPaymentApiV2PaymentsPaymentIdRefundPostSecurity:
    RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity,
): string {
  return JSON.stringify(
    RefundPaymentApiV2PaymentsPaymentIdRefundPostSecurity$outboundSchema.parse(
      refundPaymentApiV2PaymentsPaymentIdRefundPostSecurity,
    ),
  );
}

/** @internal */
export type RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest$Outbound = {
  payment_id: string;
  body: models.PaymentRefundRequest$Outbound;
};

/** @internal */
export const RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest$outboundSchema:
  z.ZodMiniType<
    RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest$Outbound,
    RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest
  > = z.pipe(
    z.object({
      paymentId: z.string(),
      body: models.PaymentRefundRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        paymentId: "payment_id",
      });
    }),
  );

export function refundPaymentApiV2PaymentsPaymentIdRefundPostRequestToJSON(
  refundPaymentApiV2PaymentsPaymentIdRefundPostRequest:
    RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest,
): string {
  return JSON.stringify(
    RefundPaymentApiV2PaymentsPaymentIdRefundPostRequest$outboundSchema.parse(
      refundPaymentApiV2PaymentsPaymentIdRefundPostRequest,
    ),
  );
}
