/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity =
  {
    jwtBearer?: string | undefined;
    apiKey?: string | undefined;
  };

export type UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest =
  {
    subscriptionId: string;
    freezeId: string;
    body: models.FreezeSubscriptionUpdateRequest;
  };

/** @internal */
export type UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity$outboundSchema:
  z.ZodMiniType<
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity$Outbound,
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function updateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurityToJSON(
  updateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity:
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity,
): string {
  return JSON.stringify(
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity$outboundSchema
      .parse(
        updateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutSecurity,
      ),
  );
}

/** @internal */
export type UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest$Outbound =
  {
    subscription_id: string;
    freeze_id: string;
    body: models.FreezeSubscriptionUpdateRequest$Outbound;
  };

/** @internal */
export const UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest$Outbound,
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      freezeId: z.string(),
      body: models.FreezeSubscriptionUpdateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
        freezeId: "freeze_id",
      });
    }),
  );

export function updateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequestToJSON(
  updateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest:
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest,
): string {
  return JSON.stringify(
    UpdateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest$outboundSchema
      .parse(
        updateSubscriptionFreezeApiV2SubscriptionsSubscriptionIdFreezeFreezeIdPutRequest,
      ),
  );
}
