/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateCouponApiV2CouponsCouponIdPutSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type UpdateCouponApiV2CouponsCouponIdPutRequest = {
  couponId: string;
  body: models.CouponUpdate;
};

/** @internal */
export type UpdateCouponApiV2CouponsCouponIdPutSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const UpdateCouponApiV2CouponsCouponIdPutSecurity$outboundSchema:
  z.ZodMiniType<
    UpdateCouponApiV2CouponsCouponIdPutSecurity$Outbound,
    UpdateCouponApiV2CouponsCouponIdPutSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function updateCouponApiV2CouponsCouponIdPutSecurityToJSON(
  updateCouponApiV2CouponsCouponIdPutSecurity:
    UpdateCouponApiV2CouponsCouponIdPutSecurity,
): string {
  return JSON.stringify(
    UpdateCouponApiV2CouponsCouponIdPutSecurity$outboundSchema.parse(
      updateCouponApiV2CouponsCouponIdPutSecurity,
    ),
  );
}

/** @internal */
export type UpdateCouponApiV2CouponsCouponIdPutRequest$Outbound = {
  coupon_id: string;
  body: models.CouponUpdate$Outbound;
};

/** @internal */
export const UpdateCouponApiV2CouponsCouponIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdateCouponApiV2CouponsCouponIdPutRequest$Outbound,
    UpdateCouponApiV2CouponsCouponIdPutRequest
  > = z.pipe(
    z.object({
      couponId: z.string(),
      body: models.CouponUpdate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        couponId: "coupon_id",
      });
    }),
  );

export function updateCouponApiV2CouponsCouponIdPutRequestToJSON(
  updateCouponApiV2CouponsCouponIdPutRequest:
    UpdateCouponApiV2CouponsCouponIdPutRequest,
): string {
  return JSON.stringify(
    UpdateCouponApiV2CouponsCouponIdPutRequest$outboundSchema.parse(
      updateCouponApiV2CouponsCouponIdPutRequest,
    ),
  );
}
