/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest = {
  subscriptionId: string;
  body: models.SubscriptionUpdate;
};

/** @internal */
export type UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity$Outbound =
  {
    JWTBearer?: string | undefined;
    APIKey?: string | undefined;
  };

/** @internal */
export const UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity$outboundSchema:
  z.ZodMiniType<
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity$Outbound,
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function updateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurityToJSON(
  updateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity:
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity,
): string {
  return JSON.stringify(
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity$outboundSchema
      .parse(updateSubscriptionApiV2SubscriptionsSubscriptionIdPutSecurity),
  );
}

/** @internal */
export type UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest$Outbound =
  {
    subscription_id: string;
    body: models.SubscriptionUpdate$Outbound;
  };

/** @internal */
export const UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest$Outbound,
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      body: models.SubscriptionUpdate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
      });
    }),
  );

export function updateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequestToJSON(
  updateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest:
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest,
): string {
  return JSON.stringify(
    UpdateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest$outboundSchema
      .parse(updateSubscriptionApiV2SubscriptionsSubscriptionIdPutRequest),
  );
}
