/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest = {
  orgConsumerId: string;
  body: models.ConsumerUpdate;
};

/** @internal */
export type UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity$outboundSchema:
  z.ZodMiniType<
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity$Outbound,
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function updateConsumerApiV2ConsumersOrgConsumerIdPutSecurityToJSON(
  updateConsumerApiV2ConsumersOrgConsumerIdPutSecurity:
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity,
): string {
  return JSON.stringify(
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutSecurity$outboundSchema.parse(
      updateConsumerApiV2ConsumersOrgConsumerIdPutSecurity,
    ),
  );
}

/** @internal */
export type UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest$Outbound = {
  org_consumer_id: string;
  body: models.ConsumerUpdate$Outbound;
};

/** @internal */
export const UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest$Outbound,
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest
  > = z.pipe(
    z.object({
      orgConsumerId: z.string(),
      body: models.ConsumerUpdate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        orgConsumerId: "org_consumer_id",
      });
    }),
  );

export function updateConsumerApiV2ConsumersOrgConsumerIdPutRequestToJSON(
  updateConsumerApiV2ConsumersOrgConsumerIdPutRequest:
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest,
): string {
  return JSON.stringify(
    UpdateConsumerApiV2ConsumersOrgConsumerIdPutRequest$outboundSchema.parse(
      updateConsumerApiV2ConsumersOrgConsumerIdPutRequest,
    ),
  );
}
