/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateProductApiV2ProductsProductIdPutSecurity = {
  jwtBearer?: string | undefined;
  apiKey?: string | undefined;
};

export type UpdateProductApiV2ProductsProductIdPutRequest = {
  productId: string;
  body: models.ProductUpdate;
};

/** @internal */
export type UpdateProductApiV2ProductsProductIdPutSecurity$Outbound = {
  JWTBearer?: string | undefined;
  APIKey?: string | undefined;
};

/** @internal */
export const UpdateProductApiV2ProductsProductIdPutSecurity$outboundSchema:
  z.ZodMiniType<
    UpdateProductApiV2ProductsProductIdPutSecurity$Outbound,
    UpdateProductApiV2ProductsProductIdPutSecurity
  > = z.pipe(
    z.object({
      jwtBearer: z.optional(z.string()),
      apiKey: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        jwtBearer: "JWTBearer",
        apiKey: "APIKey",
      });
    }),
  );

export function updateProductApiV2ProductsProductIdPutSecurityToJSON(
  updateProductApiV2ProductsProductIdPutSecurity:
    UpdateProductApiV2ProductsProductIdPutSecurity,
): string {
  return JSON.stringify(
    UpdateProductApiV2ProductsProductIdPutSecurity$outboundSchema.parse(
      updateProductApiV2ProductsProductIdPutSecurity,
    ),
  );
}

/** @internal */
export type UpdateProductApiV2ProductsProductIdPutRequest$Outbound = {
  product_id: string;
  body: models.ProductUpdate$Outbound;
};

/** @internal */
export const UpdateProductApiV2ProductsProductIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdateProductApiV2ProductsProductIdPutRequest$Outbound,
    UpdateProductApiV2ProductsProductIdPutRequest
  > = z.pipe(
    z.object({
      productId: z.string(),
      body: models.ProductUpdate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        productId: "product_id",
      });
    }),
  );

export function updateProductApiV2ProductsProductIdPutRequestToJSON(
  updateProductApiV2ProductsProductIdPutRequest:
    UpdateProductApiV2ProductsProductIdPutRequest,
): string {
  return JSON.stringify(
    UpdateProductApiV2ProductsProductIdPutRequest$outboundSchema.parse(
      updateProductApiV2ProductsProductIdPutRequest,
    ),
  );
}
