/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AppCommonDtosSharedConsumer,
  AppCommonDtosSharedConsumer$inboundSchema,
} from "./appcommondtossharedconsumer.js";
import {
  ConsumerCommunicationMethod,
  ConsumerCommunicationMethod$inboundSchema,
} from "./consumercommunicationmethod.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Language, Language$inboundSchema } from "./language.js";

export type AppCommonDtosSharedOrganizationConsumer = {
  id: string;
  name: string;
  alias?: string | null | undefined;
  email?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  preferredLanguage: Language;
  consumer?: AppCommonDtosSharedConsumer | null | undefined;
  isDeleted?: boolean | null | undefined;
  communicationMethods?: Array<ConsumerCommunicationMethod> | null | undefined;
};

/** @internal */
export const AppCommonDtosSharedOrganizationConsumer$inboundSchema:
  z.ZodMiniType<AppCommonDtosSharedOrganizationConsumer, unknown> = z.pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      alias: z.optional(z.nullable(types.string())),
      email: z.optional(z.nullable(types.string())),
      phone_number: z.optional(z.nullable(types.string())),
      preferred_language: Language$inboundSchema,
      consumer: z.optional(
        z.nullable(AppCommonDtosSharedConsumer$inboundSchema),
      ),
      is_deleted: z.optional(z.nullable(types.boolean())),
      communication_methods: z.optional(
        z.nullable(z.array(ConsumerCommunicationMethod$inboundSchema)),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "phone_number": "phoneNumber",
        "preferred_language": "preferredLanguage",
        "is_deleted": "isDeleted",
        "communication_methods": "communicationMethods",
      });
    }),
  );

export function appCommonDtosSharedOrganizationConsumerFromJSON(
  jsonString: string,
): SafeParseResult<
  AppCommonDtosSharedOrganizationConsumer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppCommonDtosSharedOrganizationConsumer$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppCommonDtosSharedOrganizationConsumer' from JSON`,
  );
}
