/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Language, Language$inboundSchema } from "./language.js";

export type AppCommonDtosSharedConsumer = {
  id: string;
  phoneNumber?: string | null | undefined;
  email?: string | null | undefined;
  preferredLanguage: Language;
};

/** @internal */
export const AppCommonDtosSharedConsumer$inboundSchema: z.ZodMiniType<
  AppCommonDtosSharedConsumer,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    phone_number: z.optional(z.nullable(types.string())),
    email: z.optional(z.nullable(types.string())),
    preferred_language: Language$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "phone_number": "phoneNumber",
      "preferred_language": "preferredLanguage",
    });
  }),
);

export function appCommonDtosSharedConsumerFromJSON(
  jsonString: string,
): SafeParseResult<AppCommonDtosSharedConsumer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppCommonDtosSharedConsumer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppCommonDtosSharedConsumer' from JSON`,
  );
}
