/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AppConsumerV2DtosConsumer = {
  id?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  preferredLanguage?: string | null | undefined;
};

/** @internal */
export const AppConsumerV2DtosConsumer$inboundSchema: z.ZodMiniType<
  AppConsumerV2DtosConsumer,
  unknown
> = z.pipe(
  z.object({
    id: z.optional(z.nullable(types.string())),
    phone_number: z.optional(z.nullable(types.string())),
    preferred_language: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "phone_number": "phoneNumber",
      "preferred_language": "preferredLanguage",
    });
  }),
);

export function appConsumerV2DtosConsumerFromJSON(
  jsonString: string,
): SafeParseResult<AppConsumerV2DtosConsumer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppConsumerV2DtosConsumer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppConsumerV2DtosConsumer' from JSON`,
  );
}
