/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AppSubscriptionV2DtosOrganizationConsumer = {
  id: string;
  name: string;
  alias?: string | null | undefined;
  email?: string | null | undefined;
};

/** @internal */
export const AppSubscriptionV2DtosOrganizationConsumer$inboundSchema:
  z.ZodMiniType<AppSubscriptionV2DtosOrganizationConsumer, unknown> = z.object({
    id: types.string(),
    name: types.string(),
    alias: z.optional(z.nullable(types.string())),
    email: z.optional(z.nullable(types.string())),
  });

export function appSubscriptionV2DtosOrganizationConsumerFromJSON(
  jsonString: string,
): SafeParseResult<
  AppSubscriptionV2DtosOrganizationConsumer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppSubscriptionV2DtosOrganizationConsumer$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppSubscriptionV2DtosOrganizationConsumer' from JSON`,
  );
}
