/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BranchDto = {
  id: string;
  name: string;
};

/** @internal */
export const BranchDto$inboundSchema: z.ZodMiniType<BranchDto, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
  });

export function branchDtoFromJSON(
  jsonString: string,
): SafeParseResult<BranchDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BranchDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BranchDto' from JSON`,
  );
}
