/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Branch = {
  id: string;
  name: string;
};

/** @internal */
export const Branch$inboundSchema: z.ZodMiniType<Branch, unknown> = z.object({
  id: types.string(),
  name: types.string(),
});

export function branchFromJSON(
  jsonString: string,
): SafeParseResult<Branch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Branch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Branch' from JSON`,
  );
}
