/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AppConsumerV2DtosConsumer,
  AppConsumerV2DtosConsumer$inboundSchema,
} from "./appconsumerv2dtosconsumer.js";
import { Branch, Branch$inboundSchema } from "./branch.js";
import {
  ConsumerCommunicationMethod,
  ConsumerCommunicationMethod$inboundSchema,
} from "./consumercommunicationmethod.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  LastInvoiceActivity,
  LastInvoiceActivity$inboundSchema,
} from "./lastinvoiceactivity.js";

export type ConsumerResponse = {
  id: string;
  name: string;
  phoneNumber?: string | null | undefined;
  email?: string | null | undefined;
  externalId?: string | null | undefined;
  consumer?: AppConsumerV2DtosConsumer | null | undefined;
  iban?: string | null | undefined;
  isDeleted: boolean;
  alias?: string | null | undefined;
  createdAt: Date;
  branch: Branch;
  comment?: string | null | undefined;
  communicationMethods: Array<ConsumerCommunicationMethod>;
  preferredLanguage: string;
  lastInvoiceActivity?: LastInvoiceActivity | null | undefined;
};

/** @internal */
export const ConsumerResponse$inboundSchema: z.ZodMiniType<
  ConsumerResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    phone_number: z.optional(z.nullable(types.string())),
    email: z.optional(z.nullable(types.string())),
    external_id: z.optional(z.nullable(types.string())),
    consumer: z.optional(z.nullable(AppConsumerV2DtosConsumer$inboundSchema)),
    iban: z.optional(z.nullable(types.string())),
    is_deleted: types.boolean(),
    alias: z.optional(z.nullable(types.string())),
    created_at: types.date(),
    branch: Branch$inboundSchema,
    comment: z.optional(z.nullable(types.string())),
    communication_methods: z.array(ConsumerCommunicationMethod$inboundSchema),
    preferred_language: types.string(),
    last_invoice_activity: z.optional(
      z.nullable(LastInvoiceActivity$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "phone_number": "phoneNumber",
      "external_id": "externalId",
      "is_deleted": "isDeleted",
      "created_at": "createdAt",
      "communication_methods": "communicationMethods",
      "preferred_language": "preferredLanguage",
      "last_invoice_activity": "lastInvoiceActivity",
    });
  }),
);

export function consumerResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConsumerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConsumerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConsumerResponse' from JSON`,
  );
}
