/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ConsumerCommunicationMethod = {
  Whatsapp: "WHATSAPP",
  Email: "EMAIL",
  Sms: "SMS",
} as const;
export type ConsumerCommunicationMethod = OpenEnum<
  typeof ConsumerCommunicationMethod
>;

/** @internal */
export const ConsumerCommunicationMethod$inboundSchema: z.ZodMiniType<
  ConsumerCommunicationMethod,
  unknown
> = openEnums.inboundSchema(ConsumerCommunicationMethod);
/** @internal */
export const ConsumerCommunicationMethod$outboundSchema: z.ZodMiniType<
  string,
  ConsumerCommunicationMethod
> = openEnums.outboundSchema(ConsumerCommunicationMethod);
