/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ConsumerCommunicationMethod,
  ConsumerCommunicationMethod$outboundSchema,
} from "./consumercommunicationmethod.js";

/**
 * Consumer update model that inherits from ConsumerCreate but makes all fields optional.
 */
export type ConsumerUpdate = {
  name?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  email?: string | null | undefined;
  externalId?: string | null | undefined;
  iban?: string | null | undefined;
  alias?: string | null | undefined;
  comment?: string | null | undefined;
  /**
   * Preferred language
   */
  preferredLanguage?: string | null | undefined;
  communicationMethods?: Array<ConsumerCommunicationMethod> | null | undefined;
};

/** @internal */
export type ConsumerUpdate$Outbound = {
  name?: string | null | undefined;
  phone_number?: string | null | undefined;
  email?: string | null | undefined;
  external_id?: string | null | undefined;
  iban?: string | null | undefined;
  alias?: string | null | undefined;
  comment?: string | null | undefined;
  preferred_language?: string | null | undefined;
  communication_methods?: Array<string> | null | undefined;
};

/** @internal */
export const ConsumerUpdate$outboundSchema: z.ZodMiniType<
  ConsumerUpdate$Outbound,
  ConsumerUpdate
> = z.pipe(
  z.object({
    name: z.optional(z.nullable(z.string())),
    phoneNumber: z.optional(z.nullable(z.string())),
    email: z.optional(z.nullable(z.string())),
    externalId: z.optional(z.nullable(z.string())),
    iban: z.optional(z.nullable(z.string())),
    alias: z.optional(z.nullable(z.string())),
    comment: z.optional(z.nullable(z.string())),
    preferredLanguage: z.optional(z.nullable(z.string())),
    communicationMethods: z.optional(
      z.nullable(z.array(ConsumerCommunicationMethod$outboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      phoneNumber: "phone_number",
      externalId: "external_id",
      preferredLanguage: "preferred_language",
      communicationMethods: "communication_methods",
    });
  }),
);

export function consumerUpdateToJSON(consumerUpdate: ConsumerUpdate): string {
  return JSON.stringify(ConsumerUpdate$outboundSchema.parse(consumerUpdate));
}
