/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ConsumerCommunicationMethod,
  ConsumerCommunicationMethod$outboundSchema,
} from "./consumercommunicationmethod.js";

/**
 * Consumer creation model.
 */
export type ConsumerCreate = {
  /**
   * Consumer name
   */
  name: string;
  /**
   * Phone number
   */
  phoneNumber?: string | null | undefined;
  /**
   * Email address
   */
  email?: string | null | undefined;
  /**
   * External ID
   */
  externalId?: string | null | undefined;
  /**
   * IBAN
   */
  iban?: string | null | undefined;
  /**
   * Alias
   */
  alias?: string | null | undefined;
  /**
   * Comment
   */
  comment?: string | null | undefined;
  /**
   * Preferred language
   */
  preferredLanguage?: string | null | undefined;
  /**
   * Communication methods
   */
  communicationMethods?: Array<ConsumerCommunicationMethod> | null | undefined;
};

/** @internal */
export type ConsumerCreate$Outbound = {
  name: string;
  phone_number?: string | null | undefined;
  email?: string | null | undefined;
  external_id?: string | null | undefined;
  iban?: string | null | undefined;
  alias?: string | null | undefined;
  comment?: string | null | undefined;
  preferred_language?: string | null | undefined;
  communication_methods?: Array<string> | null | undefined;
};

/** @internal */
export const ConsumerCreate$outboundSchema: z.ZodMiniType<
  ConsumerCreate$Outbound,
  ConsumerCreate
> = z.pipe(
  z.object({
    name: z.string(),
    phoneNumber: z.optional(z.nullable(z.string())),
    email: z.optional(z.nullable(z.string())),
    externalId: z.optional(z.nullable(z.string())),
    iban: z.optional(z.nullable(z.string())),
    alias: z.optional(z.nullable(z.string())),
    comment: z.optional(z.nullable(z.string())),
    preferredLanguage: z.optional(z.nullable(z.string())),
    communicationMethods: z.optional(
      z.nullable(z.array(ConsumerCommunicationMethod$outboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      phoneNumber: "phone_number",
      externalId: "external_id",
      preferredLanguage: "preferred_language",
      communicationMethods: "communication_methods",
    });
  }),
);

export function consumerCreateToJSON(consumerCreate: ConsumerCreate): string {
  return JSON.stringify(ConsumerCreate$outboundSchema.parse(consumerCreate));
}
