/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ContactInformationType = {
  Phone: "PHONE",
  Email: "EMAIL",
} as const;
export type ContactInformationType = OpenEnum<typeof ContactInformationType>;

/** @internal */
export const ContactInformationType$inboundSchema: z.ZodMiniType<
  ContactInformationType,
  unknown
> = openEnums.inboundSchema(ContactInformationType);
/** @internal */
export const ContactInformationType$outboundSchema: z.ZodMiniType<
  string,
  ContactInformationType
> = openEnums.outboundSchema(ContactInformationType);
