/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";

/**
 * Updated discount value (either percentage or fixed).
 */
export type CouponUpdateDiscountValue = number | string;

export type CouponUpdate = {
  /**
   * Updated name of the coupon.
   */
  name?: string | null | undefined;
  /**
   * Updated discount value (either percentage or fixed).
   */
  discountValue?: number | string | null | undefined;
  /**
   * True if the discount is a percentage, False if it is a fixed amount.
   */
  isPercentage?: boolean | null | undefined;
  /**
   * Whether the coupon should be active or inactive.
   */
  isActive?: boolean | null | undefined;
};

/** @internal */
export type CouponUpdateDiscountValue$Outbound = number | string;

/** @internal */
export const CouponUpdateDiscountValue$outboundSchema: z.ZodMiniType<
  CouponUpdateDiscountValue$Outbound,
  CouponUpdateDiscountValue
> = smartUnion([z.number(), z.string()]);

export function couponUpdateDiscountValueToJSON(
  couponUpdateDiscountValue: CouponUpdateDiscountValue,
): string {
  return JSON.stringify(
    CouponUpdateDiscountValue$outboundSchema.parse(couponUpdateDiscountValue),
  );
}

/** @internal */
export type CouponUpdate$Outbound = {
  name?: string | null | undefined;
  discount_value?: number | string | null | undefined;
  is_percentage?: boolean | null | undefined;
  is_active?: boolean | null | undefined;
};

/** @internal */
export const CouponUpdate$outboundSchema: z.ZodMiniType<
  CouponUpdate$Outbound,
  CouponUpdate
> = z.pipe(
  z.object({
    name: z.optional(z.nullable(z.string())),
    discountValue: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    isPercentage: z.optional(z.nullable(z.boolean())),
    isActive: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      discountValue: "discount_value",
      isPercentage: "is_percentage",
      isActive: "is_active",
    });
  }),
);

export function couponUpdateToJSON(couponUpdate: CouponUpdate): string {
  return JSON.stringify(CouponUpdate$outboundSchema.parse(couponUpdate));
}
