/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";

/**
 * Discount value of the coupon (either percentage or fixed).
 */
export type CouponCreateDiscountValue = number | string;

export type CouponCreate = {
  /**
   * Name of the coupon.
   */
  name: string;
  /**
   * Discount value of the coupon (either percentage or fixed).
   */
  discountValue: number | string;
  /**
   * True if the discount is a percentage, False if it is a fixed amount.
   */
  isPercentage?: boolean | undefined;
  /**
   * Indicates if the coupon is active upon creation.
   */
  isActive?: boolean | undefined;
};

/** @internal */
export type CouponCreateDiscountValue$Outbound = number | string;

/** @internal */
export const CouponCreateDiscountValue$outboundSchema: z.ZodMiniType<
  CouponCreateDiscountValue$Outbound,
  CouponCreateDiscountValue
> = smartUnion([z.number(), z.string()]);

export function couponCreateDiscountValueToJSON(
  couponCreateDiscountValue: CouponCreateDiscountValue,
): string {
  return JSON.stringify(
    CouponCreateDiscountValue$outboundSchema.parse(couponCreateDiscountValue),
  );
}

/** @internal */
export type CouponCreate$Outbound = {
  name: string;
  discount_value: number | string;
  is_percentage: boolean;
  is_active: boolean;
};

/** @internal */
export const CouponCreate$outboundSchema: z.ZodMiniType<
  CouponCreate$Outbound,
  CouponCreate
> = z.pipe(
  z.object({
    name: z.string(),
    discountValue: smartUnion([z.number(), z.string()]),
    isPercentage: z._default(z.boolean(), false),
    isActive: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      discountValue: "discount_value",
      isPercentage: "is_percentage",
      isActive: "is_active",
    });
  }),
);

export function couponCreateToJSON(couponCreate: CouponCreate): string {
  return JSON.stringify(CouponCreate$outboundSchema.parse(couponCreate));
}
