/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CouponMetadataDto = {
  couponId: string;
  name: string;
  isPercentage: boolean;
  discountValue: string;
  order: number;
  amountBeforeDiscount: string;
  discountAmount: string;
  amountAfterDiscount: string;
};

/** @internal */
export const CouponMetadataDto$inboundSchema: z.ZodMiniType<
  CouponMetadataDto,
  unknown
> = z.pipe(
  z.object({
    coupon_id: types.string(),
    name: types.string(),
    is_percentage: types.boolean(),
    discount_value: types.string(),
    order: types.number(),
    amount_before_discount: types.string(),
    discount_amount: types.string(),
    amount_after_discount: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "coupon_id": "couponId",
      "is_percentage": "isPercentage",
      "discount_value": "discountValue",
      "amount_before_discount": "amountBeforeDiscount",
      "discount_amount": "discountAmount",
      "amount_after_discount": "amountAfterDiscount",
    });
  }),
);

export function couponMetadataDtoFromJSON(
  jsonString: string,
): SafeParseResult<CouponMetadataDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CouponMetadataDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CouponMetadataDto' from JSON`,
  );
}
