/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CouponMetadataDto,
  CouponMetadataDto$inboundSchema,
} from "./couponmetadatadto.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CouponCalculationMetadataDto = {
  coupons: Array<CouponMetadataDto>;
};

/** @internal */
export const CouponCalculationMetadataDto$inboundSchema: z.ZodMiniType<
  CouponCalculationMetadataDto,
  unknown
> = z.object({
  coupons: z.array(CouponMetadataDto$inboundSchema),
});

export function couponCalculationMetadataDtoFromJSON(
  jsonString: string,
): SafeParseResult<CouponCalculationMetadataDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CouponCalculationMetadataDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CouponCalculationMetadataDto' from JSON`,
  );
}
