/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CouponDetailed = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  updatedAt: Date | null;
  id: string;
  /**
   * Name of the coupon.
   */
  name: string;
  /**
   * Discount value of the coupon (either percentage or fixed).
   */
  discountValue: string;
  /**
   * True if the discount is a percentage, False if it is a fixed amount.
   */
  isPercentage: boolean;
  /**
   * Indicates if the coupon is currently active.
   */
  isActive: boolean;
  /**
   * Indicates how many times this coupon has been used.
   */
  redemptions: number;
};

/** @internal */
export const CouponDetailed$inboundSchema: z.ZodMiniType<
  CouponDetailed,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    updated_at: types.nullable(types.date()),
    id: types.string(),
    name: types.string(),
    discount_value: types.string(),
    is_percentage: types.boolean(),
    is_active: types.boolean(),
    redemptions: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "discount_value": "discountValue",
      "is_percentage": "isPercentage",
      "is_active": "isActive",
    });
  }),
);

export function couponDetailedFromJSON(
  jsonString: string,
): SafeParseResult<CouponDetailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CouponDetailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CouponDetailed' from JSON`,
  );
}
