/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreatePaymentLinkItemDto = {
  productId: string;
  quantity?: number | undefined;
  coupons?: Array<string> | undefined;
};

/** @internal */
export type CreatePaymentLinkItemDto$Outbound = {
  product_id: string;
  quantity: number;
  coupons?: Array<string> | undefined;
};

/** @internal */
export const CreatePaymentLinkItemDto$outboundSchema: z.ZodMiniType<
  CreatePaymentLinkItemDto$Outbound,
  CreatePaymentLinkItemDto
> = z.pipe(
  z.object({
    productId: z.string(),
    quantity: z._default(z.int(), 1),
    coupons: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      productId: "product_id",
    });
  }),
);

export function createPaymentLinkItemDtoToJSON(
  createPaymentLinkItemDto: CreatePaymentLinkItemDto,
): string {
  return JSON.stringify(
    CreatePaymentLinkItemDto$outboundSchema.parse(createPaymentLinkItemDto),
  );
}
