/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ContactInformationType,
  ContactInformationType$outboundSchema,
} from "./contactinformationtype.js";
import {
  CreatePaymentLinkItemDto,
  CreatePaymentLinkItemDto$Outbound,
  CreatePaymentLinkItemDto$outboundSchema,
} from "./createpaymentlinkitemdto.js";
import {
  PaymentMethodDto,
  PaymentMethodDto$Outbound,
  PaymentMethodDto$outboundSchema,
} from "./paymentmethoddto.js";

export type CreatePaymentLinkDto = {
  name: string;
  description?: string | null | undefined;
  items: Array<CreatePaymentLinkItemDto>;
  coupons?: Array<string> | undefined;
  /**
   * Maximum number of times this payment link can be used. If null, the payment link can be used unlimited times. If organization_consumer_id is set, this number becomes how many times that specific customer can pay. Typically this should be set to 1 in that scenario.
   */
  maxNumberOfPayments?: number | null | undefined;
  /**
   * Datetime after which the payment link is no longer valid. If no timezone is specified, UTC is assumed.
   */
  validUntil?: Date | null | undefined;
  confirmationMessage?: string | null | undefined;
  /**
   * Configure which payment methods are available for customers to use when paying through this link. Each payment method type can be individually enabled or disabled. If null, the organization's default payment method settings will be used.
   */
  paymentMethods?: PaymentMethodDto | null | undefined;
  /**
   * A JSON Schema defining the custom fields.
   */
  customFields?: { [k: string]: any } | null | undefined;
  /**
   * URL to redirect the payer to after a successful payment
   */
  successRedirectUrl?: string | null | undefined;
  /**
   * URL to redirect the payer to after a failed payment
   */
  failureRedirectUrl?: string | null | undefined;
  /**
   * ID of an existing consumer who will pay using this payment link. If set, customer information is not collected and this payment will be for that customer only. This is typically used when a specific customer is paying once. If not set, the link will collect customer information first. Use this when you expect multiple payments from different people, such as for a group trip or event.
   */
  organizationConsumerId?: string | null | undefined;
  /**
   * Custom key-value metadata to be sent to payment gateway and returned in webhooks
   */
  customMetadata?: { [k: string]: any } | null | undefined;
  /**
   * Type of contact information required for payment collection (PHONE or EMAIL). Defaults to PHONE if not specified.
   */
  contactInformationType?: ContactInformationType | null | undefined;
};

/** @internal */
export type CreatePaymentLinkDto$Outbound = {
  name: string;
  description?: string | null | undefined;
  items: Array<CreatePaymentLinkItemDto$Outbound>;
  coupons?: Array<string> | undefined;
  max_number_of_payments?: number | null | undefined;
  valid_until?: string | null | undefined;
  confirmation_message?: string | null | undefined;
  payment_methods?: PaymentMethodDto$Outbound | null | undefined;
  custom_fields?: { [k: string]: any } | null | undefined;
  success_redirect_url?: string | null | undefined;
  failure_redirect_url?: string | null | undefined;
  organization_consumer_id?: string | null | undefined;
  custom_metadata?: { [k: string]: any } | null | undefined;
  contact_information_type?: string | null | undefined;
};

/** @internal */
export const CreatePaymentLinkDto$outboundSchema: z.ZodMiniType<
  CreatePaymentLinkDto$Outbound,
  CreatePaymentLinkDto
> = z.pipe(
  z.object({
    name: z.string(),
    description: z.optional(z.nullable(z.string())),
    items: z.array(CreatePaymentLinkItemDto$outboundSchema),
    coupons: z.optional(z.array(z.string())),
    maxNumberOfPayments: z.optional(z.nullable(z.int())),
    validUntil: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    confirmationMessage: z.optional(z.nullable(z.string())),
    paymentMethods: z.optional(z.nullable(PaymentMethodDto$outboundSchema)),
    customFields: z.optional(z.nullable(z.record(z.string(), z.any()))),
    successRedirectUrl: z.optional(z.nullable(z.string())),
    failureRedirectUrl: z.optional(z.nullable(z.string())),
    organizationConsumerId: z.optional(z.nullable(z.string())),
    customMetadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
    contactInformationType: z.optional(
      z.nullable(ContactInformationType$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxNumberOfPayments: "max_number_of_payments",
      validUntil: "valid_until",
      confirmationMessage: "confirmation_message",
      paymentMethods: "payment_methods",
      customFields: "custom_fields",
      successRedirectUrl: "success_redirect_url",
      failureRedirectUrl: "failure_redirect_url",
      organizationConsumerId: "organization_consumer_id",
      customMetadata: "custom_metadata",
      contactInformationType: "contact_information_type",
    });
  }),
);

export function createPaymentLinkDtoToJSON(
  createPaymentLinkDto: CreatePaymentLinkDto,
): string {
  return JSON.stringify(
    CreatePaymentLinkDto$outboundSchema.parse(createPaymentLinkDto),
  );
}
