/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type FreezeSubscriptionUpdateRequest = {
  /**
   * freeze_start_datetime is always provided even if it dont change
   */
  freezeStartDatetime: Date;
  /**
   * freeze_end_datetime is optional, if provided, it must be greater than freeze_start_datetime
   */
  freezeEndDatetime: Date | null;
  notes: string | null;
};

/** @internal */
export type FreezeSubscriptionUpdateRequest$Outbound = {
  freeze_start_datetime: string;
  freeze_end_datetime: string | null;
  notes: string | null;
};

/** @internal */
export const FreezeSubscriptionUpdateRequest$outboundSchema: z.ZodMiniType<
  FreezeSubscriptionUpdateRequest$Outbound,
  FreezeSubscriptionUpdateRequest
> = z.pipe(
  z.object({
    freezeStartDatetime: z.pipe(z.date(), z.transform(v => v.toISOString())),
    freezeEndDatetime: z.nullable(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    notes: z.nullable(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      freezeStartDatetime: "freeze_start_datetime",
      freezeEndDatetime: "freeze_end_datetime",
    });
  }),
);

export function freezeSubscriptionUpdateRequestToJSON(
  freezeSubscriptionUpdateRequest: FreezeSubscriptionUpdateRequest,
): string {
  return JSON.stringify(
    FreezeSubscriptionUpdateRequest$outboundSchema.parse(
      freezeSubscriptionUpdateRequest,
    ),
  );
}
