/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type FreezeSubscriptionCreateRequest = {
  freezeStartDatetime: Date;
  freezeEndDatetime?: Date | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export type FreezeSubscriptionCreateRequest$Outbound = {
  freeze_start_datetime: string;
  freeze_end_datetime?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export const FreezeSubscriptionCreateRequest$outboundSchema: z.ZodMiniType<
  FreezeSubscriptionCreateRequest$Outbound,
  FreezeSubscriptionCreateRequest
> = z.pipe(
  z.object({
    freezeStartDatetime: z.pipe(z.date(), z.transform(v => v.toISOString())),
    freezeEndDatetime: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    notes: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      freezeStartDatetime: "freeze_start_datetime",
      freezeEndDatetime: "freeze_end_datetime",
    });
  }),
);

export function freezeSubscriptionCreateRequestToJSON(
  freezeSubscriptionCreateRequest: FreezeSubscriptionCreateRequest,
): string {
  return JSON.stringify(
    FreezeSubscriptionCreateRequest$outboundSchema.parse(
      freezeSubscriptionCreateRequest,
    ),
  );
}
