/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FreezeSubscriptionBase = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  updatedAt: Date | null;
  id: string;
  freezeStartDatetime: Date;
  freezeEndDatetime?: Date | null | undefined;
  notes?: string | null | undefined;
  subscriptionId: string;
  invoiceId: string;
  duration?: number | null | undefined;
};

/** @internal */
export const FreezeSubscriptionBase$inboundSchema: z.ZodMiniType<
  FreezeSubscriptionBase,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    updated_at: types.nullable(types.date()),
    id: types.string(),
    freeze_start_datetime: types.date(),
    freeze_end_datetime: z.optional(z.nullable(types.date())),
    notes: z.optional(z.nullable(types.string())),
    subscription_id: types.string(),
    invoice_id: types.string(),
    duration: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "freeze_start_datetime": "freezeStartDatetime",
      "freeze_end_datetime": "freezeEndDatetime",
      "subscription_id": "subscriptionId",
      "invoice_id": "invoiceId",
    });
  }),
);

export function freezeSubscriptionBaseFromJSON(
  jsonString: string,
): SafeParseResult<FreezeSubscriptionBase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FreezeSubscriptionBase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FreezeSubscriptionBase' from JSON`,
  );
}
