/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InvoicePaymentMethodDto = {
  /**
   * mada is enabled
   */
  mada: boolean;
  /**
   * visa is enabled
   */
  visa: boolean;
  /**
   * mastercard is enabled
   */
  mastercard: boolean;
  /**
   * amex is enabled
   */
  amex: boolean;
  /**
   * bank_transfer is enabled
   */
  bankTransfer: boolean;
  /**
   * installment is enabled
   */
  installment: boolean;
};

/** @internal */
export const InvoicePaymentMethodDto$inboundSchema: z.ZodMiniType<
  InvoicePaymentMethodDto,
  unknown
> = z.pipe(
  z.object({
    mada: types.boolean(),
    visa: types.boolean(),
    mastercard: types.boolean(),
    amex: types.boolean(),
    bank_transfer: types.boolean(),
    installment: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "bank_transfer": "bankTransfer",
    });
  }),
);

export function invoicePaymentMethodDtoFromJSON(
  jsonString: string,
): SafeParseResult<InvoicePaymentMethodDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoicePaymentMethodDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoicePaymentMethodDto' from JSON`,
  );
}
