/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  InvoiceStatusEnum,
  InvoiceStatusEnum$outboundSchema,
} from "./invoicestatusenum.js";
import {
  PaymentStatusEnum,
  PaymentStatusEnum$outboundSchema,
} from "./paymentstatusenum.js";

export type InvoiceListFiltersFromPrice = number | string;

export type InvoiceListFiltersToPrice = number | string;

export type InvoiceListFilters = {
  includePayments?: boolean | null | undefined;
  paymentLinkId?: string | null | undefined;
  statuses?: Array<InvoiceStatusEnum> | null | undefined;
  /**
   * Invoice includes payments with the following statuses
   */
  paymentStatuses?: Array<PaymentStatusEnum> | null | undefined;
  searchTerm?: string | null | undefined;
  fromDate?: Date | null | undefined;
  toDate?: Date | null | undefined;
  /**
   * Invoice's payment due date from this date onwards
   */
  dueDateFrom?: Date | null | undefined;
  /**
   * Invoice's payment due date to this date or older
   */
  dueDateTo?: Date | null | undefined;
  fromPrice?: number | string | null | undefined;
  toPrice?: number | string | null | undefined;
  organizationConsumerId?: string | null | undefined;
  subscriptionId?: string | null | undefined;
};

/** @internal */
export type InvoiceListFiltersFromPrice$Outbound = number | string;

/** @internal */
export const InvoiceListFiltersFromPrice$outboundSchema: z.ZodMiniType<
  InvoiceListFiltersFromPrice$Outbound,
  InvoiceListFiltersFromPrice
> = smartUnion([z.number(), z.string()]);

export function invoiceListFiltersFromPriceToJSON(
  invoiceListFiltersFromPrice: InvoiceListFiltersFromPrice,
): string {
  return JSON.stringify(
    InvoiceListFiltersFromPrice$outboundSchema.parse(
      invoiceListFiltersFromPrice,
    ),
  );
}

/** @internal */
export type InvoiceListFiltersToPrice$Outbound = number | string;

/** @internal */
export const InvoiceListFiltersToPrice$outboundSchema: z.ZodMiniType<
  InvoiceListFiltersToPrice$Outbound,
  InvoiceListFiltersToPrice
> = smartUnion([z.number(), z.string()]);

export function invoiceListFiltersToPriceToJSON(
  invoiceListFiltersToPrice: InvoiceListFiltersToPrice,
): string {
  return JSON.stringify(
    InvoiceListFiltersToPrice$outboundSchema.parse(invoiceListFiltersToPrice),
  );
}

/** @internal */
export type InvoiceListFilters$Outbound = {
  include_payments?: boolean | null | undefined;
  payment_link_id?: string | null | undefined;
  statuses?: Array<string> | null | undefined;
  payment_statuses?: Array<string> | null | undefined;
  search_term?: string | null | undefined;
  from_date?: string | null | undefined;
  to_date?: string | null | undefined;
  due_date_from?: string | null | undefined;
  due_date_to?: string | null | undefined;
  from_price?: number | string | null | undefined;
  to_price?: number | string | null | undefined;
  organization_consumer_id?: string | null | undefined;
  subscription_id?: string | null | undefined;
};

/** @internal */
export const InvoiceListFilters$outboundSchema: z.ZodMiniType<
  InvoiceListFilters$Outbound,
  InvoiceListFilters
> = z.pipe(
  z.object({
    includePayments: z.optional(z.nullable(z.boolean())),
    paymentLinkId: z.optional(z.nullable(z.string())),
    statuses: z.optional(z.nullable(z.array(InvoiceStatusEnum$outboundSchema))),
    paymentStatuses: z.optional(
      z.nullable(z.array(PaymentStatusEnum$outboundSchema)),
    ),
    searchTerm: z.optional(z.nullable(z.string())),
    fromDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    toDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    dueDateFrom: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    dueDateTo: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    fromPrice: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    toPrice: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    organizationConsumerId: z.optional(z.nullable(z.string())),
    subscriptionId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      includePayments: "include_payments",
      paymentLinkId: "payment_link_id",
      paymentStatuses: "payment_statuses",
      searchTerm: "search_term",
      fromDate: "from_date",
      toDate: "to_date",
      dueDateFrom: "due_date_from",
      dueDateTo: "due_date_to",
      fromPrice: "from_price",
      toPrice: "to_price",
      organizationConsumerId: "organization_consumer_id",
      subscriptionId: "subscription_id",
    });
  }),
);

export function invoiceListFiltersToJSON(
  invoiceListFilters: InvoiceListFilters,
): string {
  return JSON.stringify(
    InvoiceListFilters$outboundSchema.parse(invoiceListFilters),
  );
}
