/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Invoice type enum representing the payment structure/pattern of an invoice.
 *
 * @remarks
 *
 * Type describes how the invoice is structured for payments (ONE_OFF, RECURRING, INSTALLMENTS, etc.).
 * This is determined at invoice creation and typically doesn't change. Different from InvoiceStatusEnum
 * which describes the current lifecycle state of the invoice.
 */
export const InvoiceType = {
  OneOff: "ONE_OFF",
  OneOffFuture: "ONE_OFF_FUTURE",
  Recurring: "RECURRING",
  Installments: "INSTALLMENTS",
} as const;
/**
 * Invoice type enum representing the payment structure/pattern of an invoice.
 *
 * @remarks
 *
 * Type describes how the invoice is structured for payments (ONE_OFF, RECURRING, INSTALLMENTS, etc.).
 * This is determined at invoice creation and typically doesn't change. Different from InvoiceStatusEnum
 * which describes the current lifecycle state of the invoice.
 */
export type InvoiceType = OpenEnum<typeof InvoiceType>;

/** @internal */
export const InvoiceType$inboundSchema: z.ZodMiniType<InvoiceType, unknown> =
  openEnums.inboundSchema(InvoiceType);
