/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Invoice status enum representing the lifecycle/state of an invoice.
 *
 * @remarks
 *
 * Status describes the current stage of an invoice in its lifecycle (DRAFT → CREATED → SENT → ACCEPTED → COMPLETED).
 * This changes over time as the invoice progresses. Different from InvoiceType which describes the payment structure.
 */
export const InvoiceStatusEnum = {
  Draft: "DRAFT",
  Created: "CREATED",
  Sent: "SENT",
  Accepted: "ACCEPTED",
  Rejected: "REJECTED",
  Completed: "COMPLETED",
  Canceled: "CANCELED",
  Expired: "EXPIRED",
} as const;
/**
 * Invoice status enum representing the lifecycle/state of an invoice.
 *
 * @remarks
 *
 * Status describes the current stage of an invoice in its lifecycle (DRAFT → CREATED → SENT → ACCEPTED → COMPLETED).
 * This changes over time as the invoice progresses. Different from InvoiceType which describes the payment structure.
 */
export type InvoiceStatusEnum = OpenEnum<typeof InvoiceStatusEnum>;

/** @internal */
export const InvoiceStatusEnum$inboundSchema: z.ZodMiniType<
  InvoiceStatusEnum,
  unknown
> = openEnums.inboundSchema(InvoiceStatusEnum);
/** @internal */
export const InvoiceStatusEnum$outboundSchema: z.ZodMiniType<
  string,
  InvoiceStatusEnum
> = openEnums.outboundSchema(InvoiceStatusEnum);
