/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SubscriptionRecurringInterval,
  SubscriptionRecurringInterval$inboundSchema,
} from "./subscriptionrecurringinterval.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$inboundSchema,
} from "./subscriptionstatus.js";

export type InvoiceListSubscrptionDto = {
  id: string;
  recurringInterval: SubscriptionRecurringInterval;
  recurringIntervalCount: number;
  status: SubscriptionStatus;
  currentPeriodStart: Date;
  currentPeriodEnd?: Date | null | undefined;
  cancelAtPeriodEnd: boolean;
};

/** @internal */
export const InvoiceListSubscrptionDto$inboundSchema: z.ZodMiniType<
  InvoiceListSubscrptionDto,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    recurring_interval: SubscriptionRecurringInterval$inboundSchema,
    recurring_interval_count: types.number(),
    status: SubscriptionStatus$inboundSchema,
    current_period_start: types.date(),
    current_period_end: z.optional(z.nullable(types.date())),
    cancel_at_period_end: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "recurring_interval": "recurringInterval",
      "recurring_interval_count": "recurringIntervalCount",
      "current_period_start": "currentPeriodStart",
      "current_period_end": "currentPeriodEnd",
      "cancel_at_period_end": "cancelAtPeriodEnd",
    });
  }),
);

export function invoiceListSubscrptionDtoFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceListSubscrptionDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceListSubscrptionDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceListSubscrptionDto' from JSON`,
  );
}
