/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const Language = {
  Ar: "AR",
  En: "EN",
} as const;
export type Language = OpenEnum<typeof Language>;

/** @internal */
export const Language$inboundSchema: z.ZodMiniType<Language, unknown> =
  openEnums.inboundSchema(Language);
