/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type LastInvoiceActivity = {
  id: string;
  orgInvoiceNumber: number;
  subcriptionId?: string | null | undefined;
};

/** @internal */
export const LastInvoiceActivity$inboundSchema: z.ZodMiniType<
  LastInvoiceActivity,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    org_invoice_number: types.number(),
    subcription_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "org_invoice_number": "orgInvoiceNumber",
      "subcription_id": "subcriptionId",
    });
  }),
);

export function lastInvoiceActivityFromJSON(
  jsonString: string,
): SafeParseResult<LastInvoiceActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LastInvoiceActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LastInvoiceActivity' from JSON`,
  );
}
