/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ConsumerResponse,
  ConsumerResponse$inboundSchema,
} from "./consumerresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type ListResourceConsumerResponse = {
  data: Array<ConsumerResponse>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceConsumerResponse$inboundSchema: z.ZodMiniType<
  ListResourceConsumerResponse,
  unknown
> = z.object({
  data: z.array(ConsumerResponse$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceConsumerResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceConsumerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceConsumerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceConsumerResponse' from JSON`,
  );
}
