/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import {
  SubscriptionDetailed,
  SubscriptionDetailed$inboundSchema,
} from "./subscriptiondetailed.js";

export type ListResourceSubscriptionDetailed = {
  data: Array<SubscriptionDetailed>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceSubscriptionDetailed$inboundSchema: z.ZodMiniType<
  ListResourceSubscriptionDetailed,
  unknown
> = z.object({
  data: z.array(SubscriptionDetailed$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceSubscriptionDetailedFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceSubscriptionDetailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceSubscriptionDetailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceSubscriptionDetailed' from JSON`,
  );
}
