/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FreezeSubscriptionBase,
  FreezeSubscriptionBase$inboundSchema,
} from "./freezesubscriptionbase.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type ListResourceFreezeSubscriptionBase = {
  data: Array<FreezeSubscriptionBase>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceFreezeSubscriptionBase$inboundSchema: z.ZodMiniType<
  ListResourceFreezeSubscriptionBase,
  unknown
> = z.object({
  data: z.array(FreezeSubscriptionBase$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceFreezeSubscriptionBaseFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceFreezeSubscriptionBase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListResourceFreezeSubscriptionBase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceFreezeSubscriptionBase' from JSON`,
  );
}
