/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  InvoiceListItem,
  InvoiceListItem$inboundSchema,
} from "./invoicelistitem.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type ListResourceInvoiceListItem = {
  data: Array<InvoiceListItem>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceInvoiceListItem$inboundSchema: z.ZodMiniType<
  ListResourceInvoiceListItem,
  unknown
> = z.object({
  data: z.array(InvoiceListItem$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceInvoiceListItemFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceInvoiceListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceInvoiceListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceInvoiceListItem' from JSON`,
  );
}
