/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import { ProductDto, ProductDto$inboundSchema } from "./productdto.js";

export type ListResourceProductDto = {
  data: Array<ProductDto>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceProductDto$inboundSchema: z.ZodMiniType<
  ListResourceProductDto,
  unknown
> = z.object({
  data: z.array(ProductDto$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceProductDtoFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceProductDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceProductDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceProductDto' from JSON`,
  );
}
