/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CouponDetailed,
  CouponDetailed$inboundSchema,
} from "./coupondetailed.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type ListResourceCouponDetailed = {
  data: Array<CouponDetailed>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceCouponDetailed$inboundSchema: z.ZodMiniType<
  ListResourceCouponDetailed,
  unknown
> = z.object({
  data: z.array(CouponDetailed$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceCouponDetailedFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceCouponDetailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceCouponDetailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceCouponDetailed' from JSON`,
  );
}
