/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import {
  PaymentLinkDetailed,
  PaymentLinkDetailed$inboundSchema,
} from "./paymentlinkdetailed.js";

export type ListResourcePaymentLinkDetailed = {
  data: Array<PaymentLinkDetailed>;
  pagination: Pagination;
};

/** @internal */
export const ListResourcePaymentLinkDetailed$inboundSchema: z.ZodMiniType<
  ListResourcePaymentLinkDetailed,
  unknown
> = z.object({
  data: z.array(PaymentLinkDetailed$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourcePaymentLinkDetailedFromJSON(
  jsonString: string,
): SafeParseResult<ListResourcePaymentLinkDetailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourcePaymentLinkDetailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourcePaymentLinkDetailed' from JSON`,
  );
}
