/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Pagination = {
  totalCount: number;
  maxPage: number;
  currentPage: number;
  limit: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .pipe(
    z.object({
      total_count: types.number(),
      max_page: types.number(),
      current_page: types.number(),
      limit: types.number(),
      has_next_page: types.boolean(),
      has_previous_page: types.boolean(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "total_count": "totalCount",
        "max_page": "maxPage",
        "current_page": "currentPage",
        "has_next_page": "hasNextPage",
        "has_previous_page": "hasPreviousPage",
      });
    }),
  );

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}
