/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentStatusEnum = {
  Pending: "PENDING",
  Processing: "PROCESSING",
  FailedInitiation: "FAILED_INITIATION",
  Succeeded: "SUCCEEDED",
  Failed: "FAILED",
  Canceled: "CANCELED",
  UnderReview: "UNDER_REVIEW",
  Expired: "EXPIRED",
  Settled: "SETTLED",
  Refunded: "REFUNDED",
} as const;
export type PaymentStatusEnum = OpenEnum<typeof PaymentStatusEnum>;

/** @internal */
export const PaymentStatusEnum$inboundSchema: z.ZodMiniType<
  PaymentStatusEnum,
  unknown
> = openEnums.inboundSchema(PaymentStatusEnum);
/** @internal */
export const PaymentStatusEnum$outboundSchema: z.ZodMiniType<
  string,
  PaymentStatusEnum
> = openEnums.outboundSchema(PaymentStatusEnum);
