/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ContactInformationType,
  ContactInformationType$inboundSchema,
} from "./contactinformationtype.js";
import {
  CouponCalculationMetadataDto,
  CouponCalculationMetadataDto$inboundSchema,
} from "./couponcalculationmetadatadto.js";
import { CouponDto, CouponDto$inboundSchema } from "./coupondto.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PaymentLinkItemDto,
  PaymentLinkItemDto$inboundSchema,
} from "./paymentlinkitemdto.js";
import {
  PaymentLinkStatus,
  PaymentLinkStatus$inboundSchema,
} from "./paymentlinkstatus.js";
import {
  PaymentMethodDto,
  PaymentMethodDto$inboundSchema,
} from "./paymentmethoddto.js";
import {
  SubscriptionRecurringInterval,
  SubscriptionRecurringInterval$inboundSchema,
} from "./subscriptionrecurringinterval.js";

export type PaymentLinkDetailed = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  updatedAt: Date | null;
  id: string;
  name: string;
  description?: string | null | undefined;
  amount: string;
  originalAmount: string;
  itemLevelDiscountedAmount: string;
  /**
   * Metadata about how coupons were applied to the payment link
   */
  couponCalculationMetadata?: CouponCalculationMetadataDto | null | undefined;
  currency: string;
  maxNumberOfPayments?: number | null | undefined;
  /**
   * UTC datetime after which the payment link is no longer valid
   */
  validUntil?: Date | null | undefined;
  confirmationMessage?: string | null | undefined;
  recurringInterval?: SubscriptionRecurringInterval | null | undefined;
  recurringIntervalCount?: number | null | undefined;
  status: PaymentLinkStatus;
  organizationId: string;
  userId: string;
  organizationConsumerId?: string | null | undefined;
  deactivateMessage?: string | null | undefined;
  customFields?: { [k: string]: any } | null | undefined;
  successRedirectUrl?: string | null | undefined;
  failureRedirectUrl?: string | null | undefined;
  /**
   * Custom key-value metadata to be sent to payment gateway and returned in webhooks
   */
  customMetadata?: { [k: string]: any } | null | undefined;
  /**
   * Type of contact information required for payment collection (PHONE or EMAIL)
   */
  contactInformationType?: ContactInformationType | null | undefined;
  items: Array<PaymentLinkItemDto>;
  coupons: Array<CouponDto>;
  overridePaymentMethods?: PaymentMethodDto | null | undefined;
  url?: string | null | undefined;
  /**
   * Total amount collected from payments
   */
  amountCollected?: string | undefined;
};

/** @internal */
export const PaymentLinkDetailed$inboundSchema: z.ZodMiniType<
  PaymentLinkDetailed,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    updated_at: types.nullable(types.date()),
    id: types.string(),
    name: types.string(),
    description: z.optional(z.nullable(types.string())),
    amount: types.string(),
    original_amount: types.string(),
    item_level_discounted_amount: types.string(),
    coupon_calculation_metadata: z.optional(
      z.nullable(CouponCalculationMetadataDto$inboundSchema),
    ),
    currency: types.string(),
    max_number_of_payments: z.optional(z.nullable(types.number())),
    valid_until: z.optional(z.nullable(types.date())),
    confirmation_message: z.optional(z.nullable(types.string())),
    recurring_interval: z.optional(
      z.nullable(SubscriptionRecurringInterval$inboundSchema),
    ),
    recurring_interval_count: z.optional(z.nullable(types.number())),
    status: PaymentLinkStatus$inboundSchema,
    organization_id: types.string(),
    user_id: types.string(),
    organization_consumer_id: z.optional(z.nullable(types.string())),
    deactivate_message: z.optional(z.nullable(types.string())),
    custom_fields: z.optional(z.nullable(z.record(z.string(), z.any()))),
    success_redirect_url: z.optional(z.nullable(types.string())),
    failure_redirect_url: z.optional(z.nullable(types.string())),
    custom_metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
    contact_information_type: z.optional(
      z.nullable(ContactInformationType$inboundSchema),
    ),
    items: z.array(PaymentLinkItemDto$inboundSchema),
    coupons: z.array(CouponDto$inboundSchema),
    override_payment_methods: z.optional(
      z.nullable(PaymentMethodDto$inboundSchema),
    ),
    url: z.optional(z.nullable(types.string())),
    amount_collected: z._default(types.string(), "0"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "original_amount": "originalAmount",
      "item_level_discounted_amount": "itemLevelDiscountedAmount",
      "coupon_calculation_metadata": "couponCalculationMetadata",
      "max_number_of_payments": "maxNumberOfPayments",
      "valid_until": "validUntil",
      "confirmation_message": "confirmationMessage",
      "recurring_interval": "recurringInterval",
      "recurring_interval_count": "recurringIntervalCount",
      "organization_id": "organizationId",
      "user_id": "userId",
      "organization_consumer_id": "organizationConsumerId",
      "deactivate_message": "deactivateMessage",
      "custom_fields": "customFields",
      "success_redirect_url": "successRedirectUrl",
      "failure_redirect_url": "failureRedirectUrl",
      "custom_metadata": "customMetadata",
      "contact_information_type": "contactInformationType",
      "override_payment_methods": "overridePaymentMethods",
      "amount_collected": "amountCollected",
    });
  }),
);

export function paymentLinkDetailedFromJSON(
  jsonString: string,
): SafeParseResult<PaymentLinkDetailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentLinkDetailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentLinkDetailed' from JSON`,
  );
}
