/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentRefundReason = {
  RequestedByCustomer: "REQUESTED_BY_CUSTOMER",
  Duplicate: "DUPLICATE",
  Fraudlent: "FRAUDLENT",
  Other: "OTHER",
} as const;
export type PaymentRefundReason = OpenEnum<typeof PaymentRefundReason>;

/** @internal */
export const PaymentRefundReason$inboundSchema: z.ZodMiniType<
  PaymentRefundReason,
  unknown
> = openEnums.inboundSchema(PaymentRefundReason);
/** @internal */
export const PaymentRefundReason$outboundSchema: z.ZodMiniType<
  string,
  PaymentRefundReason
> = openEnums.outboundSchema(PaymentRefundReason);
