/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentTypeEnum = {
  Initial: "INITIAL",
  Installment: "INSTALLMENT",
} as const;
export type PaymentTypeEnum = OpenEnum<typeof PaymentTypeEnum>;

/** @internal */
export const PaymentTypeEnum$inboundSchema: z.ZodMiniType<
  PaymentTypeEnum,
  unknown
> = openEnums.inboundSchema(PaymentTypeEnum);
