/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentLinkStatus = {
  Inactive: "INACTIVE",
  Active: "ACTIVE",
  Completed: "COMPLETED",
} as const;
export type PaymentLinkStatus = OpenEnum<typeof PaymentLinkStatus>;

/** @internal */
export const PaymentLinkStatus$inboundSchema: z.ZodMiniType<
  PaymentLinkStatus,
  unknown
> = openEnums.inboundSchema(PaymentLinkStatus);
/** @internal */
export const PaymentLinkStatus$outboundSchema: z.ZodMiniType<
  string,
  PaymentLinkStatus
> = openEnums.outboundSchema(PaymentLinkStatus);
