/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PaymentMethod, PaymentMethod$inboundSchema } from "./paymentmethod.js";
import {
  PaymentRefundReason,
  PaymentRefundReason$inboundSchema,
} from "./paymentrefundreason.js";
import {
  PaymentStatusEnum,
  PaymentStatusEnum$inboundSchema,
} from "./paymentstatusenum.js";
import {
  PaymentTypeEnum,
  PaymentTypeEnum$inboundSchema,
} from "./paymenttypeenum.js";

export type PaymentResponse = {
  id: string;
  amount: string;
  scheduledOn: string;
  type: PaymentTypeEnum;
  paymentMethod?: PaymentMethod | null | undefined;
  currentStatus: PaymentStatusEnum;
  payedAt?: Date | null | undefined;
  refundedAt?: Date | null | undefined;
  refundReason?: PaymentRefundReason | null | undefined;
  refundNote?: string | null | undefined;
};

/** @internal */
export const PaymentResponse$inboundSchema: z.ZodMiniType<
  PaymentResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    amount: types.string(),
    scheduled_on: types.string(),
    type: PaymentTypeEnum$inboundSchema,
    payment_method: z.optional(z.nullable(PaymentMethod$inboundSchema)),
    current_status: PaymentStatusEnum$inboundSchema,
    payed_at: z.optional(z.nullable(types.date())),
    refunded_at: z.optional(z.nullable(types.date())),
    refund_reason: z.optional(z.nullable(PaymentRefundReason$inboundSchema)),
    refund_note: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "scheduled_on": "scheduledOn",
      "payment_method": "paymentMethod",
      "current_status": "currentStatus",
      "payed_at": "payedAt",
      "refunded_at": "refundedAt",
      "refund_reason": "refundReason",
      "refund_note": "refundNote",
    });
  }),
);

export function paymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentResponse' from JSON`,
  );
}
