/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentMethodEnum = {
  Openbanking: "OPENBANKING",
  Paymentgateway: "PAYMENTGATEWAY",
} as const;
export type PaymentMethodEnum = OpenEnum<typeof PaymentMethodEnum>;

/** @internal */
export const PaymentMethodEnum$inboundSchema: z.ZodMiniType<
  PaymentMethodEnum,
  unknown
> = openEnums.inboundSchema(PaymentMethodEnum);
