/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  PaymentLinkStatus,
  PaymentLinkStatus$outboundSchema,
} from "./paymentlinkstatus.js";

/**
 * limit list by min payment link total amount inclusive
 */
export type PaymentLinkListFiltersFromPrice = number | string;

/**
 * limit list by max payment link total amount inclusive
 */
export type PaymentLinkListFiltersToPrice = number | string;

export type PaymentLinkListFilters = {
  /**
   * Filter by subscription status
   */
  statuses?: Array<PaymentLinkStatus> | null | undefined;
  /**
   * datetime is created_at
   */
  fromDate?: Date | null | undefined;
  /**
   * datetime is created_at
   */
  toDate?: Date | null | undefined;
  /**
   * limit list by min payment link total amount inclusive
   */
  fromPrice?: number | string | null | undefined;
  /**
   * limit list by max payment link total amount inclusive
   */
  toPrice?: number | string | null | undefined;
  /**
   * Product ids that need to be in the list of payment links
   */
  productIds?: Array<string> | null | undefined;
};

/** @internal */
export type PaymentLinkListFiltersFromPrice$Outbound = number | string;

/** @internal */
export const PaymentLinkListFiltersFromPrice$outboundSchema: z.ZodMiniType<
  PaymentLinkListFiltersFromPrice$Outbound,
  PaymentLinkListFiltersFromPrice
> = smartUnion([z.number(), z.string()]);

export function paymentLinkListFiltersFromPriceToJSON(
  paymentLinkListFiltersFromPrice: PaymentLinkListFiltersFromPrice,
): string {
  return JSON.stringify(
    PaymentLinkListFiltersFromPrice$outboundSchema.parse(
      paymentLinkListFiltersFromPrice,
    ),
  );
}

/** @internal */
export type PaymentLinkListFiltersToPrice$Outbound = number | string;

/** @internal */
export const PaymentLinkListFiltersToPrice$outboundSchema: z.ZodMiniType<
  PaymentLinkListFiltersToPrice$Outbound,
  PaymentLinkListFiltersToPrice
> = smartUnion([z.number(), z.string()]);

export function paymentLinkListFiltersToPriceToJSON(
  paymentLinkListFiltersToPrice: PaymentLinkListFiltersToPrice,
): string {
  return JSON.stringify(
    PaymentLinkListFiltersToPrice$outboundSchema.parse(
      paymentLinkListFiltersToPrice,
    ),
  );
}

/** @internal */
export type PaymentLinkListFilters$Outbound = {
  statuses?: Array<string> | null | undefined;
  from_date?: string | null | undefined;
  to_date?: string | null | undefined;
  from_price?: number | string | null | undefined;
  to_price?: number | string | null | undefined;
  product_ids?: Array<string> | null | undefined;
};

/** @internal */
export const PaymentLinkListFilters$outboundSchema: z.ZodMiniType<
  PaymentLinkListFilters$Outbound,
  PaymentLinkListFilters
> = z.pipe(
  z.object({
    statuses: z.optional(z.nullable(z.array(PaymentLinkStatus$outboundSchema))),
    fromDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    toDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    fromPrice: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    toPrice: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    productIds: z.optional(z.nullable(z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      fromDate: "from_date",
      toDate: "to_date",
      fromPrice: "from_price",
      toPrice: "to_price",
      productIds: "product_ids",
    });
  }),
);

export function paymentLinkListFiltersToJSON(
  paymentLinkListFilters: PaymentLinkListFilters,
): string {
  return JSON.stringify(
    PaymentLinkListFilters$outboundSchema.parse(paymentLinkListFilters),
  );
}
