/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PaymentMethod, PaymentMethod$inboundSchema } from "./paymentmethod.js";
import {
  PaymentStatusEnum,
  PaymentStatusEnum$inboundSchema,
} from "./paymentstatusenum.js";
import {
  PaymentTypeEnum,
  PaymentTypeEnum$inboundSchema,
} from "./paymenttypeenum.js";

export type PaymentDto = {
  id: string;
  amount: string;
  currency: string;
  scheduledOn: Date;
  invoicePaymentNumber: number;
  type: PaymentTypeEnum;
  paymentMethod?: PaymentMethod | null | undefined;
  currentStatus: PaymentStatusEnum;
  payedAt?: Date | null | undefined;
  settledAt?: Date | null | undefined;
  refundedAt?: Date | null | undefined;
  pdfLink?: string | null | undefined;
  paidToAccountId?: string | null | undefined;
};

/** @internal */
export const PaymentDto$inboundSchema: z.ZodMiniType<PaymentDto, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      amount: types.string(),
      currency: types.string(),
      scheduled_on: types.date(),
      invoice_payment_number: types.number(),
      type: PaymentTypeEnum$inboundSchema,
      payment_method: z.optional(z.nullable(PaymentMethod$inboundSchema)),
      current_status: PaymentStatusEnum$inboundSchema,
      payed_at: z.optional(z.nullable(types.date())),
      settled_at: z.optional(z.nullable(types.date())),
      refunded_at: z.optional(z.nullable(types.date())),
      pdf_link: z.optional(z.nullable(types.string())),
      paid_to_account_id: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "scheduled_on": "scheduledOn",
        "invoice_payment_number": "invoicePaymentNumber",
        "payment_method": "paymentMethod",
        "current_status": "currentStatus",
        "payed_at": "payedAt",
        "settled_at": "settledAt",
        "refunded_at": "refundedAt",
        "pdf_link": "pdfLink",
        "paid_to_account_id": "paidToAccountId",
      });
    }),
  );

export function paymentDtoFromJSON(
  jsonString: string,
): SafeParseResult<PaymentDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentDto' from JSON`,
  );
}
