/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentMethod = {
  Mada: "MADA",
  Mastercard: "MASTERCARD",
  Visa: "VISA",
  ApplePay: "APPLE_PAY",
  Amex: "AMEX",
  Cash: "CASH",
  PgwCardUnspecified: "PGW_CARD_UNSPECIFIED",
  BankTransfer: "BANK_TRANSFER",
  Card: "CARD",
  Qurrah: "QURRAH",
} as const;
export type PaymentMethod = OpenEnum<typeof PaymentMethod>;

/** @internal */
export const PaymentMethod$inboundSchema: z.ZodMiniType<
  PaymentMethod,
  unknown
> = openEnums.inboundSchema(PaymentMethod);
