/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PaymentFlow = {
  All: "ALL",
  Auto: "AUTO",
  Manual: "MANUAL",
} as const;
export type PaymentFlow = OpenEnum<typeof PaymentFlow>;

/** @internal */
export const PaymentFlow$inboundSchema: z.ZodMiniType<PaymentFlow, unknown> =
  openEnums.inboundSchema(PaymentFlow);
