/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  PaymentRefundReason,
  PaymentRefundReason$outboundSchema,
} from "./paymentrefundreason.js";

export type PaymentRefundRequest = {
  refundReason: PaymentRefundReason;
  refundNote?: string | null | undefined;
};

/** @internal */
export type PaymentRefundRequest$Outbound = {
  refund_reason: string;
  refund_note?: string | null | undefined;
};

/** @internal */
export const PaymentRefundRequest$outboundSchema: z.ZodMiniType<
  PaymentRefundRequest$Outbound,
  PaymentRefundRequest
> = z.pipe(
  z.object({
    refundReason: PaymentRefundReason$outboundSchema,
    refundNote: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      refundReason: "refund_reason",
      refundNote: "refund_note",
    });
  }),
);

export function paymentRefundRequestToJSON(
  paymentRefundRequest: PaymentRefundRequest,
): string {
  return JSON.stringify(
    PaymentRefundRequest$outboundSchema.parse(paymentRefundRequest),
  );
}
