/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PaymentMethodDto = {
  /**
   * visa is enabled
   */
  visa?: boolean | undefined;
  /**
   * mastercard is enabled
   */
  mastercard?: boolean | undefined;
  /**
   * amex is enabled
   */
  amex?: boolean | undefined;
  /**
   * bank_transfer is enabled
   */
  bankTransfer?: boolean | undefined;
  /**
   * installment is enabled
   */
  installment?: boolean | undefined;
};

/** @internal */
export const PaymentMethodDto$inboundSchema: z.ZodMiniType<
  PaymentMethodDto,
  unknown
> = z.pipe(
  z.object({
    visa: z._default(types.boolean(), false),
    mastercard: z._default(types.boolean(), false),
    amex: z._default(types.boolean(), false),
    bank_transfer: z._default(types.boolean(), false),
    installment: z._default(types.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      "bank_transfer": "bankTransfer",
    });
  }),
);
/** @internal */
export type PaymentMethodDto$Outbound = {
  visa: boolean;
  mastercard: boolean;
  amex: boolean;
  bank_transfer: boolean;
  installment: boolean;
};

/** @internal */
export const PaymentMethodDto$outboundSchema: z.ZodMiniType<
  PaymentMethodDto$Outbound,
  PaymentMethodDto
> = z.pipe(
  z.object({
    visa: z._default(z.boolean(), false),
    mastercard: z._default(z.boolean(), false),
    amex: z._default(z.boolean(), false),
    bankTransfer: z._default(z.boolean(), false),
    installment: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      bankTransfer: "bank_transfer",
    });
  }),
);

export function paymentMethodDtoToJSON(
  paymentMethodDto: PaymentMethodDto,
): string {
  return JSON.stringify(
    PaymentMethodDto$outboundSchema.parse(paymentMethodDto),
  );
}
export function paymentMethodDtoFromJSON(
  jsonString: string,
): SafeParseResult<PaymentMethodDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentMethodDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentMethodDto' from JSON`,
  );
}
