/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PaymentResponse,
  PaymentResponse$inboundSchema,
} from "./paymentresponse.js";

export type PaymentListResponse = {
  data: Array<PaymentResponse>;
};

/** @internal */
export const PaymentListResponse$inboundSchema: z.ZodMiniType<
  PaymentListResponse,
  unknown
> = z.object({
  data: z.array(PaymentResponse$inboundSchema),
});

export function paymentListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentListResponse' from JSON`,
  );
}
