/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { ProductType, ProductType$outboundSchema } from "./producttype.js";
import {
  RecurringInterval,
  RecurringInterval$outboundSchema,
} from "./recurringinterval.js";

/**
 * Price of the product.
 */
export type ProductCreatePrice = number | string;

export type ProductCreate = {
  /**
   * Name of the product.
   */
  name: string;
  /**
   * Description of the product.
   */
  description?: string | null | undefined;
  /**
   * Price of the product.
   */
  price: number | string;
  /**
   * Will this product be used only one time in one invoice?
   */
  isOneTime?: boolean | undefined;
  type: ProductType;
  /**
   * Represents the billing cycle interval if product is recurring
   */
  recurringInterval?: RecurringInterval | null | undefined;
  /**
   * The billing cycle multiple if the product is recurring
   */
  recurringIntervalCount?: number | undefined;
  /**
   * Is the price exempt from VAT?
   */
  isPriceExemptFromVat?: boolean | null | undefined;
  /**
   * Is the price inclusive of VAT?
   */
  isPriceInclusiveOfVat?: boolean | null | undefined;
};

/** @internal */
export type ProductCreatePrice$Outbound = number | string;

/** @internal */
export const ProductCreatePrice$outboundSchema: z.ZodMiniType<
  ProductCreatePrice$Outbound,
  ProductCreatePrice
> = smartUnion([z.number(), z.string()]);

export function productCreatePriceToJSON(
  productCreatePrice: ProductCreatePrice,
): string {
  return JSON.stringify(
    ProductCreatePrice$outboundSchema.parse(productCreatePrice),
  );
}

/** @internal */
export type ProductCreate$Outbound = {
  name: string;
  description?: string | null | undefined;
  price: number | string;
  is_one_time: boolean;
  type: string;
  recurring_interval?: string | null | undefined;
  recurring_interval_count: number;
  is_price_exempt_from_vat?: boolean | null | undefined;
  is_price_inclusive_of_vat?: boolean | null | undefined;
};

/** @internal */
export const ProductCreate$outboundSchema: z.ZodMiniType<
  ProductCreate$Outbound,
  ProductCreate
> = z.pipe(
  z.object({
    name: z.string(),
    description: z.optional(z.nullable(z.string())),
    price: smartUnion([z.number(), z.string()]),
    isOneTime: z._default(z.boolean(), false),
    type: ProductType$outboundSchema,
    recurringInterval: z.optional(z.nullable(RecurringInterval$outboundSchema)),
    recurringIntervalCount: z._default(z.int(), 1),
    isPriceExemptFromVat: z.optional(z.nullable(z.boolean())),
    isPriceInclusiveOfVat: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      isOneTime: "is_one_time",
      recurringInterval: "recurring_interval",
      recurringIntervalCount: "recurring_interval_count",
      isPriceExemptFromVat: "is_price_exempt_from_vat",
      isPriceInclusiveOfVat: "is_price_inclusive_of_vat",
    });
  }),
);

export function productCreateToJSON(productCreate: ProductCreate): string {
  return JSON.stringify(ProductCreate$outboundSchema.parse(productCreate));
}
