/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { ProductType, ProductType$outboundSchema } from "./producttype.js";
import {
  RecurringInterval,
  RecurringInterval$outboundSchema,
} from "./recurringinterval.js";

/**
 * Price of the product.
 */
export type ProductUpdatePrice = number | string;

export type ProductUpdate = {
  /**
   * Name of the product.
   */
  name?: string | null | undefined;
  /**
   * Description of the product.
   */
  description?: string | null | undefined;
  /**
   * Price of the product.
   */
  price?: number | string | null | undefined;
  /**
   * Whether the product is active. If `true`, the product won't be available for purchase anymore. Existing customers will still have access to the product details in the invoice, and subscriptions will continue normally.
   */
  isActive?: boolean | null | undefined;
  /**
   * the type of product: one off or recurring
   */
  type?: ProductType | null | undefined;
  /**
   * Represents the billing cycle interval if product is recurring
   */
  recurringInterval?: RecurringInterval | null | undefined;
  /**
   * The billing cycle multiple if the product is recurring
   */
  recurringIntervalCount?: number | null | undefined;
  /**
   * Is the price exempt from VAT?
   */
  isPriceExemptFromVat?: boolean | null | undefined;
  /**
   * Is the price inclusive of VAT?
   */
  isPriceInclusiveOfVat?: boolean | null | undefined;
};

/** @internal */
export type ProductUpdatePrice$Outbound = number | string;

/** @internal */
export const ProductUpdatePrice$outboundSchema: z.ZodMiniType<
  ProductUpdatePrice$Outbound,
  ProductUpdatePrice
> = smartUnion([z.number(), z.string()]);

export function productUpdatePriceToJSON(
  productUpdatePrice: ProductUpdatePrice,
): string {
  return JSON.stringify(
    ProductUpdatePrice$outboundSchema.parse(productUpdatePrice),
  );
}

/** @internal */
export type ProductUpdate$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
  price?: number | string | null | undefined;
  is_active?: boolean | null | undefined;
  type?: string | null | undefined;
  recurring_interval?: string | null | undefined;
  recurring_interval_count?: number | null | undefined;
  is_price_exempt_from_vat?: boolean | null | undefined;
  is_price_inclusive_of_vat?: boolean | null | undefined;
};

/** @internal */
export const ProductUpdate$outboundSchema: z.ZodMiniType<
  ProductUpdate$Outbound,
  ProductUpdate
> = z.pipe(
  z.object({
    name: z.optional(z.nullable(z.string())),
    description: z.optional(z.nullable(z.string())),
    price: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    isActive: z.optional(z.nullable(z.boolean())),
    type: z.optional(z.nullable(ProductType$outboundSchema)),
    recurringInterval: z.optional(z.nullable(RecurringInterval$outboundSchema)),
    recurringIntervalCount: z.optional(z.nullable(z.int())),
    isPriceExemptFromVat: z.optional(z.nullable(z.boolean())),
    isPriceInclusiveOfVat: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      isActive: "is_active",
      recurringInterval: "recurring_interval",
      recurringIntervalCount: "recurring_interval_count",
      isPriceExemptFromVat: "is_price_exempt_from_vat",
      isPriceInclusiveOfVat: "is_price_inclusive_of_vat",
    });
  }),
);

export function productUpdateToJSON(productUpdate: ProductUpdate): string {
  return JSON.stringify(ProductUpdate$outboundSchema.parse(productUpdate));
}
