/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ProductType = {
  Recurring: "RECURRING",
  OneOff: "ONE_OFF",
} as const;
export type ProductType = OpenEnum<typeof ProductType>;

/** @internal */
export const ProductType$inboundSchema: z.ZodMiniType<ProductType, unknown> =
  openEnums.inboundSchema(ProductType);
/** @internal */
export const ProductType$outboundSchema: z.ZodMiniType<string, ProductType> =
  openEnums.outboundSchema(ProductType);
