/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ProductType, ProductType$outboundSchema } from "./producttype.js";

export type ProductListFilters = {
  /**
   * Serach by product name or description.
   */
  searchTerm?: string | null | undefined;
  /**
   * Filter by active or inactive product. Removing this flag will return all products.
   */
  active?: boolean | null | undefined;
  /**
   * Filter by product type.
   */
  type?: ProductType | null | undefined;
};

/** @internal */
export type ProductListFilters$Outbound = {
  search_term?: string | null | undefined;
  active?: boolean | null | undefined;
  type?: string | null | undefined;
};

/** @internal */
export const ProductListFilters$outboundSchema: z.ZodMiniType<
  ProductListFilters$Outbound,
  ProductListFilters
> = z.pipe(
  z.object({
    searchTerm: z.optional(z.nullable(z.string())),
    active: z.optional(z.nullable(z.boolean())),
    type: z.optional(z.nullable(ProductType$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      searchTerm: "search_term",
    });
  }),
);

export function productListFiltersToJSON(
  productListFilters: ProductListFilters,
): string {
  return JSON.stringify(
    ProductListFilters$outboundSchema.parse(productListFilters),
  );
}
