/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const RecurrencePattern = {
  Hour: "Hour",
  Day: "Day",
  Week: "Week",
  Fortnight: "Fortnight",
  Month: "Month",
  Quarter: "Quarter",
  HalfYear: "Half-Year",
  Year: "Year",
} as const;
export type RecurrencePattern = OpenEnum<typeof RecurrencePattern>;

/** @internal */
export const RecurrencePattern$inboundSchema: z.ZodMiniType<
  RecurrencePattern,
  unknown
> = openEnums.inboundSchema(RecurrencePattern);
