/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const RecurringInterval = {
  Week: "WEEK",
  Month: "MONTH",
  Semester: "SEMESTER",
  Year: "YEAR",
} as const;
export type RecurringInterval = OpenEnum<typeof RecurringInterval>;

/** @internal */
export const RecurringInterval$inboundSchema: z.ZodMiniType<
  RecurringInterval,
  unknown
> = openEnums.inboundSchema(RecurringInterval);
/** @internal */
export const RecurringInterval$outboundSchema: z.ZodMiniType<
  string,
  RecurringInterval
> = openEnums.outboundSchema(RecurringInterval);
