/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  SubscriptionItemCreateDto,
  SubscriptionItemCreateDto$Outbound,
  SubscriptionItemCreateDto$outboundSchema,
} from "./subscriptionitemcreatedto.js";
import {
  SubscriptionPaymentMethodDto,
  SubscriptionPaymentMethodDto$Outbound,
  SubscriptionPaymentMethodDto$outboundSchema,
} from "./subscriptionpaymentmethoddto.js";

export type SubscriptionUpdate = {
  /**
   * Description of the subscription.
   */
  description?: string | null | undefined;
  /**
   * products to purchaseIf you want to keep existing items, include them in the list.
   */
  items: Array<SubscriptionItemCreateDto>;
  /**
   * coupons to apply to the subscription for discounts.If you want to keep existing coupons, include them in the list.
   */
  coupons: Array<string>;
  /**
   * specify how many cycles the subscription will last for  until it moves to canceled state automatically. Sending 'null' will cancel it.
   */
  untilCycleNumber?: number | null | undefined;
  /**
   * overriden payment methods for generated invoices for the payer - sending 'null' for any value means we should follow organization global settings for that method
   */
  overridePaymentMethods?: SubscriptionPaymentMethodDto | null | undefined;
};

/** @internal */
export type SubscriptionUpdate$Outbound = {
  description?: string | null | undefined;
  items: Array<SubscriptionItemCreateDto$Outbound>;
  coupons: Array<string>;
  until_cycle_number?: number | null | undefined;
  override_payment_methods?:
    | SubscriptionPaymentMethodDto$Outbound
    | null
    | undefined;
};

/** @internal */
export const SubscriptionUpdate$outboundSchema: z.ZodMiniType<
  SubscriptionUpdate$Outbound,
  SubscriptionUpdate
> = z.pipe(
  z.object({
    description: z.optional(z.nullable(z.string())),
    items: z.array(SubscriptionItemCreateDto$outboundSchema),
    coupons: z.array(z.string()),
    untilCycleNumber: z.optional(z.nullable(z.int())),
    overridePaymentMethods: z.optional(
      z.nullable(SubscriptionPaymentMethodDto$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      untilCycleNumber: "until_cycle_number",
      overridePaymentMethods: "override_payment_methods",
    });
  }),
);

export function subscriptionUpdateToJSON(
  subscriptionUpdate: SubscriptionUpdate,
): string {
  return JSON.stringify(
    SubscriptionUpdate$outboundSchema.parse(subscriptionUpdate),
  );
}
