/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$outboundSchema,
} from "./subscriptionstatus.js";

/**
 * limit list by min subscription amount inclusive
 */
export type SubscriptionListFiltersFromPrice = number | string;

/**
 * limit list by max subscription amount inclusive
 */
export type SubscriptionListFiltersToPrice = number | string;

export type SubscriptionListFilters = {
  /**
   * Filter by subscription status
   */
  statuses?: Array<SubscriptionStatus> | null | undefined;
  /**
   * Filter subscriptions based on if their latest invoice is paid or partially paid
   */
  latestInvoiceIsPaid?: boolean | null | undefined;
  /**
   * datetime is created_at
   */
  fromDate?: Date | null | undefined;
  /**
   * datetime is created_at
   */
  toDate?: Date | null | undefined;
  /**
   * datetime is current_period_start
   */
  currentPeriodStartFromDate?: Date | null | undefined;
  /**
   * limit list by min subscription amount inclusive
   */
  fromPrice?: number | string | null | undefined;
  /**
   * limit list by max subscription amount inclusive
   */
  toPrice?: number | string | null | undefined;
  /**
   * filter subscriptions that belongs to organization consumer
   */
  organizationConsumerId?: string | null | undefined;
  /**
   * Serach by product name or description.
   */
  searchTerm?: string | null | undefined;
  /**
   * Product ids that need to be in the list of subscriptions
   */
  productIds?: Array<string> | null | undefined;
};

/** @internal */
export type SubscriptionListFiltersFromPrice$Outbound = number | string;

/** @internal */
export const SubscriptionListFiltersFromPrice$outboundSchema: z.ZodMiniType<
  SubscriptionListFiltersFromPrice$Outbound,
  SubscriptionListFiltersFromPrice
> = smartUnion([z.number(), z.string()]);

export function subscriptionListFiltersFromPriceToJSON(
  subscriptionListFiltersFromPrice: SubscriptionListFiltersFromPrice,
): string {
  return JSON.stringify(
    SubscriptionListFiltersFromPrice$outboundSchema.parse(
      subscriptionListFiltersFromPrice,
    ),
  );
}

/** @internal */
export type SubscriptionListFiltersToPrice$Outbound = number | string;

/** @internal */
export const SubscriptionListFiltersToPrice$outboundSchema: z.ZodMiniType<
  SubscriptionListFiltersToPrice$Outbound,
  SubscriptionListFiltersToPrice
> = smartUnion([z.number(), z.string()]);

export function subscriptionListFiltersToPriceToJSON(
  subscriptionListFiltersToPrice: SubscriptionListFiltersToPrice,
): string {
  return JSON.stringify(
    SubscriptionListFiltersToPrice$outboundSchema.parse(
      subscriptionListFiltersToPrice,
    ),
  );
}

/** @internal */
export type SubscriptionListFilters$Outbound = {
  statuses?: Array<string> | null | undefined;
  latest_invoice_is_paid?: boolean | null | undefined;
  from_date?: string | null | undefined;
  to_date?: string | null | undefined;
  current_period_start_from_date?: string | null | undefined;
  from_price?: number | string | null | undefined;
  to_price?: number | string | null | undefined;
  organization_consumer_id?: string | null | undefined;
  search_term?: string | null | undefined;
  product_ids?: Array<string> | null | undefined;
};

/** @internal */
export const SubscriptionListFilters$outboundSchema: z.ZodMiniType<
  SubscriptionListFilters$Outbound,
  SubscriptionListFilters
> = z.pipe(
  z.object({
    statuses: z.optional(
      z.nullable(z.array(SubscriptionStatus$outboundSchema)),
    ),
    latestInvoiceIsPaid: z.optional(z.nullable(z.boolean())),
    fromDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    toDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    currentPeriodStartFromDate: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    fromPrice: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    toPrice: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
    organizationConsumerId: z.optional(z.nullable(z.string())),
    searchTerm: z.optional(z.nullable(z.string())),
    productIds: z.optional(z.nullable(z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      latestInvoiceIsPaid: "latest_invoice_is_paid",
      fromDate: "from_date",
      toDate: "to_date",
      currentPeriodStartFromDate: "current_period_start_from_date",
      fromPrice: "from_price",
      toPrice: "to_price",
      organizationConsumerId: "organization_consumer_id",
      searchTerm: "search_term",
      productIds: "product_ids",
    });
  }),
);

export function subscriptionListFiltersToJSON(
  subscriptionListFilters: SubscriptionListFilters,
): string {
  return JSON.stringify(
    SubscriptionListFilters$outboundSchema.parse(subscriptionListFilters),
  );
}
