/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type SubscriptionItemCreateDto = {
  productId: string;
  /**
   * Quantity must be greater than 0
   */
  quantity: number;
  /**
   * coupons to apply to this specific item for discounts.
   */
  coupons?: Array<string> | null | undefined;
};

/** @internal */
export type SubscriptionItemCreateDto$Outbound = {
  product_id: string;
  quantity: number;
  coupons?: Array<string> | null | undefined;
};

/** @internal */
export const SubscriptionItemCreateDto$outboundSchema: z.ZodMiniType<
  SubscriptionItemCreateDto$Outbound,
  SubscriptionItemCreateDto
> = z.pipe(
  z.object({
    productId: z.string(),
    quantity: z.int(),
    coupons: z.optional(z.nullable(z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      productId: "product_id",
    });
  }),
);

export function subscriptionItemCreateDtoToJSON(
  subscriptionItemCreateDto: SubscriptionItemCreateDto,
): string {
  return JSON.stringify(
    SubscriptionItemCreateDto$outboundSchema.parse(subscriptionItemCreateDto),
  );
}
