/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SubscriptionPaymentMethodDto = {
  /**
   * override visa from global settings
   */
  visa?: boolean | null | undefined;
  /**
   * override mastercard from global settings
   */
  mastercard?: boolean | null | undefined;
  /**
   * override amex from global settings
   */
  amex?: boolean | null | undefined;
  /**
   * override bank_transfer from global settings
   */
  bankTransfer?: boolean | null | undefined;
  /**
   * override installment from global settings
   */
  installment?: boolean | null | undefined;
  /**
   * Override organization's subscription auto renewal setting. If True, subscription will auto-renew at the end of each period. If False, subscription will be canceled at the end of the current period. If None (default), uses organization's subscription_auto_renewal setting.
   */
  subscriptionAutoRenewal?: boolean | null | undefined;
};

/** @internal */
export const SubscriptionPaymentMethodDto$inboundSchema: z.ZodMiniType<
  SubscriptionPaymentMethodDto,
  unknown
> = z.pipe(
  z.object({
    visa: z.optional(z.nullable(types.boolean())),
    mastercard: z.optional(z.nullable(types.boolean())),
    amex: z.optional(z.nullable(types.boolean())),
    bank_transfer: z.optional(z.nullable(types.boolean())),
    installment: z.optional(z.nullable(types.boolean())),
    subscription_auto_renewal: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "bank_transfer": "bankTransfer",
      "subscription_auto_renewal": "subscriptionAutoRenewal",
    });
  }),
);
/** @internal */
export type SubscriptionPaymentMethodDto$Outbound = {
  visa?: boolean | null | undefined;
  mastercard?: boolean | null | undefined;
  amex?: boolean | null | undefined;
  bank_transfer?: boolean | null | undefined;
  installment?: boolean | null | undefined;
  subscription_auto_renewal?: boolean | null | undefined;
};

/** @internal */
export const SubscriptionPaymentMethodDto$outboundSchema: z.ZodMiniType<
  SubscriptionPaymentMethodDto$Outbound,
  SubscriptionPaymentMethodDto
> = z.pipe(
  z.object({
    visa: z.optional(z.nullable(z.boolean())),
    mastercard: z.optional(z.nullable(z.boolean())),
    amex: z.optional(z.nullable(z.boolean())),
    bankTransfer: z.optional(z.nullable(z.boolean())),
    installment: z.optional(z.nullable(z.boolean())),
    subscriptionAutoRenewal: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      bankTransfer: "bank_transfer",
      subscriptionAutoRenewal: "subscription_auto_renewal",
    });
  }),
);

export function subscriptionPaymentMethodDtoToJSON(
  subscriptionPaymentMethodDto: SubscriptionPaymentMethodDto,
): string {
  return JSON.stringify(
    SubscriptionPaymentMethodDto$outboundSchema.parse(
      subscriptionPaymentMethodDto,
    ),
  );
}
export function subscriptionPaymentMethodDtoFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionPaymentMethodDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionPaymentMethodDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionPaymentMethodDto' from JSON`,
  );
}
