/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type SubscriptionCancel = {
  /**
   * Whether or not to cancel all the related invoices to this subscription. If False, only the subscription will be canceled but the related invoices will remain untouched.
   */
  cancelRelatedInvoices?: boolean | undefined;
};

/** @internal */
export type SubscriptionCancel$Outbound = {
  cancel_related_invoices: boolean;
};

/** @internal */
export const SubscriptionCancel$outboundSchema: z.ZodMiniType<
  SubscriptionCancel$Outbound,
  SubscriptionCancel
> = z.pipe(
  z.object({
    cancelRelatedInvoices: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      cancelRelatedInvoices: "cancel_related_invoices",
    });
  }),
);

export function subscriptionCancelToJSON(
  subscriptionCancel: SubscriptionCancel,
): string {
  return JSON.stringify(
    SubscriptionCancel$outboundSchema.parse(subscriptionCancel),
  );
}
