/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  SubscriptionItemCreateDto,
  SubscriptionItemCreateDto$Outbound,
  SubscriptionItemCreateDto$outboundSchema,
} from "./subscriptionitemcreatedto.js";
import {
  SubscriptionPaymentMethodDto,
  SubscriptionPaymentMethodDto$Outbound,
  SubscriptionPaymentMethodDto$outboundSchema,
} from "./subscriptionpaymentmethoddto.js";

export type SubscriptionCreate = {
  /**
   * send notification to consumer about subscription first invoice
   */
  notifyConsumer?: boolean | undefined;
  /**
   * Description of the subscription.
   */
  description?: string | null | undefined;
  /**
   * products to purchase.
   */
  items: Array<SubscriptionItemCreateDto>;
  /**
   * coupons to apply to the subscription for discounts.
   */
  coupons?: Array<string> | null | undefined;
  /**
   * consumer who is going to subscribe
   */
  organizationConsumerId: string;
  /**
   * starting date of first subscription cycle
   */
  periodStart: Date;
  /**
   * specify how many cycles the subscription will last for  until it moves to canceled state automatically
   */
  untilCycleNumber?: number | null | undefined;
  /**
   * overriden payment methods for generated invoices for the payer - sending 'null' for any value means we should follow organization global settings for that method
   */
  overridePaymentMethods?: SubscriptionPaymentMethodDto | null | undefined;
  /**
   * if enabled, all applied coupons on subscription level or item level will be excluded, and payer needs to pay full amount of the created invoice when they pay by installments.
   */
  excludeCouponsIfInstallments?: boolean | undefined;
};

/** @internal */
export type SubscriptionCreate$Outbound = {
  notify_consumer: boolean;
  description?: string | null | undefined;
  items: Array<SubscriptionItemCreateDto$Outbound>;
  coupons?: Array<string> | null | undefined;
  organization_consumer_id: string;
  period_start: string;
  until_cycle_number?: number | null | undefined;
  override_payment_methods?:
    | SubscriptionPaymentMethodDto$Outbound
    | null
    | undefined;
  exclude_coupons_if_installments: boolean;
};

/** @internal */
export const SubscriptionCreate$outboundSchema: z.ZodMiniType<
  SubscriptionCreate$Outbound,
  SubscriptionCreate
> = z.pipe(
  z.object({
    notifyConsumer: z._default(z.boolean(), true),
    description: z.optional(z.nullable(z.string())),
    items: z.array(SubscriptionItemCreateDto$outboundSchema),
    coupons: z.optional(z.nullable(z.array(z.string()))),
    organizationConsumerId: z.string(),
    periodStart: z.pipe(z.date(), z.transform(v => v.toISOString())),
    untilCycleNumber: z.optional(z.nullable(z.int())),
    overridePaymentMethods: z.optional(
      z.nullable(SubscriptionPaymentMethodDto$outboundSchema),
    ),
    excludeCouponsIfInstallments: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      notifyConsumer: "notify_consumer",
      organizationConsumerId: "organization_consumer_id",
      periodStart: "period_start",
      untilCycleNumber: "until_cycle_number",
      overridePaymentMethods: "override_payment_methods",
      excludeCouponsIfInstallments: "exclude_coupons_if_installments",
    });
  }),
);

export function subscriptionCreateToJSON(
  subscriptionCreate: SubscriptionCreate,
): string {
  return JSON.stringify(
    SubscriptionCreate$outboundSchema.parse(subscriptionCreate),
  );
}
