/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CouponCalculationMetadataDto,
  CouponCalculationMetadataDto$inboundSchema,
} from "./couponcalculationmetadatadto.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ProductDto, ProductDto$inboundSchema } from "./productdto.js";

export type SubscriptionItemDto = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  updatedAt: Date | null;
  id: string;
  productId: string;
  subscriptionId: string;
  quantity: number;
  originalAmount: string;
  discountedAmount: string;
  /**
   * Metadata about how coupons were applied to this item
   */
  couponCalculationMetadata?: CouponCalculationMetadataDto | null | undefined;
  product: ProductDto;
};

/** @internal */
export const SubscriptionItemDto$inboundSchema: z.ZodMiniType<
  SubscriptionItemDto,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    updated_at: types.nullable(types.date()),
    id: types.string(),
    product_id: types.string(),
    subscription_id: types.string(),
    quantity: types.number(),
    original_amount: types.string(),
    discounted_amount: types.string(),
    coupon_calculation_metadata: z.optional(
      z.nullable(CouponCalculationMetadataDto$inboundSchema),
    ),
    product: ProductDto$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "product_id": "productId",
      "subscription_id": "subscriptionId",
      "original_amount": "originalAmount",
      "discounted_amount": "discountedAmount",
      "coupon_calculation_metadata": "couponCalculationMetadata",
    });
  }),
);

export function subscriptionItemDtoFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionItemDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionItemDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionItemDto' from JSON`,
  );
}
