/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const SubscriptionStatus = {
  Inactive: "INACTIVE",
  Active: "ACTIVE",
  Expired: "EXPIRED",
  Canceled: "CANCELED",
  Frozen: "FROZEN",
} as const;
export type SubscriptionStatus = OpenEnum<typeof SubscriptionStatus>;

/** @internal */
export const SubscriptionStatus$inboundSchema: z.ZodMiniType<
  SubscriptionStatus,
  unknown
> = openEnums.inboundSchema(SubscriptionStatus);
/** @internal */
export const SubscriptionStatus$outboundSchema: z.ZodMiniType<
  string,
  SubscriptionStatus
> = openEnums.outboundSchema(SubscriptionStatus);
